Repository nmstate/nmstate, pull requests merged in 2020-10, with the labels that each got.

#1345 InfiniBand: Add support of IP over InfiniBand
  automation/README.md
  examples/infiniband_pkey_ipoib_create.yml
  examples/infiniband_pkey_ipoib_delete.yml
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/infiniband.py
  libnmstate/nm/infiniband.py
  libnmstate/nm/plugin.py
  libnmstate/nm/profile.py
  libnmstate/nm/translator.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  tests/integration/examples_test.py
  tests/integration/infiniband_test.py
  tests/integration/testlib/assertlib.py
  tests/integration/testlib/examplelib.py
  tests/lib/ifaces/infiniband_test.py
  tests/lib/nm/translator_test.py
  tests/lib/schema_validation_test.py
Labels: Consumer_QE_Approved, High priority, New Feature, Wait_QE

#1363 [nmstate-0.2] nm, ovs: Fix report crash when OVS has dup iface names
  libnmstate/nm/ovs.py
  tests/integration/ovs_test.py
  tests/lib/nm/ovs_test.py
Labels: Highest priority, Wait_Review

#1372 CI container: Fix the centos-stream-nmstate-dev container
  packaging/Dockerfile.centos-stream-nmstate-dev
Labels: Wait_Review

#1377 vlan: Raise exception if base iface is infiniband.
  libnmstate/ifaces/ifaces.py
  tests/lib/ifaces/vlan_iface_test.py
  tests/lib/ifaces/vxlan_iface_test.py
Labels: Waiting_Rebase

#1381 DNS: Allowing unmixed dual stack name servers
  libnmstate/dns.py
  tests/integration/dns_test.py
  tests/lib/dns_test.py
Labels: Wait_Review

#1380 nipsor: Use nispor for bond query
  libnmstate/ifaces/bond.py
  libnmstate/nispor/bond.py
  libnmstate/nm/bond.py
  libnmstate/nm/plugin.py
  libnmstate/nm/profile.py
  tests/integration/bond_test.py
  tests/integration/dynamic_ip_test.py
  tests/integration/nm/bond_test.py
  tests/integration/vxlan_test.py
  tests/lib/nm/bond_test.py
Labels: Wait_Review

#1383 ovsdb plugin: Don't add new interface
  libnmstate/nmstate.py
  libnmstate/plugin.py
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  tests/integration/nm/ovs_test.py
  tests/lib/plugin_test.py
Labels: Highest priority, Wait_Review

#1386 [nmstate-0.2] CHANGELOG: New release 0.2.11
  CHANGELOG
Labels: Wait_Review

#1389 bond: Ignore bond option verification failure
  libnmstate/ifaces/bond.py
  libnmstate/ifaces/ifaces.py
  tests/integration/bond_test.py
  tests/lib/ifaces/bond_iface_test.py
Labels: Wait_Review

#1390 [nmstate-0.3] CHANGELOG: Update changelog for 0.3.6 release
  CHANGELOG
Labels: Wait_Review

#1382 Container: Fix centos-stream-nmstate-dev image
  packaging/Dockerfile.centos-stream-nmstate-dev
Labels: Wait_Review

#1392 nm bond: Ignore ad_actor_system=00:00:00:00:00:00
  libnmstate/nm/bond.py
  tests/integration/nm/bond_test.py
Labels: Backport_Candicate, Wait_Review

#1358 CHANGELOG: New release 0.4.1
  CHANGELOG
Labels: Consumer_QE_Approved, Wait_Other_PR, Wait_QE

#1396 [nmstate-0.3] VERSION: Bump to 0.3.7
  libnmstate/VERSION
Labels: Wait_Review

#1395 VERSION: Bump to 0.4.2
  libnmstate/VERSION
Labels: Wait_Review

#1397 [nmstate-0.3] nm bond: Ignore ad_actor_system=00:00:00:00:00:00
  libnmstate/nm/bond.py
  tests/integration/nm/bond_test.py
Labels: Wait_Review

#1393 team: deprecate 'ports' in favor of 'port'
  examples/team0_with_port.yml
  libnmstate/ifaces/team.py
  libnmstate/nm/team.py
  libnmstate/schema.py
Labels: Waiting_Rebase

#1400 replace link in stale.yml with correct link
  .github/stale.yml
Labels: Waiting_Rebase

#1401 vrf: Allow vrf port to hold IP information
  libnmstate/ifaces/base_iface.py
  tests/integration/vrf_test.py
Labels: Highest priority, Wait_Review
