Repository nmstate/nmstate, pull requests merged in 2020-03, with the labels that each got.

#874 ConnectionProfile: Use interface name from NM.RemoteConnection
  libnmstate/nm/connection.py
Labels: backport candidate

#870 netapplier: retry verification after failing
  libnmstate/netapplier.py
  tests/integration/dynamic_ip_test.py
Labels: High priority, Wait_Review, backport candidate

#877 test: Grouping important test cases as tier1
  tests/integration/bond_test.py
  tests/integration/dns_test.py
  tests/integration/dynamic_ip_test.py
  tests/integration/ethernet_mtu_test.py
  tests/integration/examples_test.py
  tests/integration/linux_bridge_test.py
  tests/integration/mem_leak_test.py
  tests/integration/ovs_test.py
  tests/integration/profile_test.py
  tests/integration/route_test.py
  tests/integration/static_ip_address_test.py
  tests/integration/team_test.py
  tests/integration/timeout_test.py
  tests/integration/vlan_test.py
  tests/integration/vxlan_test.py
Labels: Wait_Review

#879 travis: fix rpmdb problem
  automation/run-tests.sh
  packaging/Dockerfile.centos8-nmstate-dev
  packaging/Dockerfile.fedora-nmstate-dev
Labels: Wait_Review

#894 automation: compare packaging againts upstream branch
  automation/run-tests.sh
Labels: Wait_Review, backport candidate

#887 containers: replace docker.io hub with quay.io hub
  automation/README.md
  automation/run-tests.sh
  packaging/README-container-registry.md
  packaging/README-dockerhub.md
  packaging/build-container.sh
Labels: Wait_Review, backport candidate

#898 travis: use quay.io repository in travis
  .travis.yml
Labels: Wait_Review

#896 test: Add test case for switching bond mode
  tests/integration/bond_test.py
  tests/integration/testlib/bondlib.py
Labels: Low priority

#910 nm applier: only create ethernet when explicitly
  libnmstate/netapplier.py
  libnmstate/nm/applier.py
  tests/integration/bond_test.py
  tests/integration/ethernet_mtu_test.py
  tests/integration/linux_bridge_test.py
  tests/integration/nm/ipv4_test.py
  tests/lib/netapplier_test.py
Labels: High priority, Wait_Review

#914 test: Add file descriptor leak check on libnmstate.apply()
  tests/integration/mem_leak_test.py
Labels: Low priority, Wait_Review

#913 state: An empty dict value is treated as an overwrite
  libnmstate/state.py
  tests/integration/testlib/bridgelib.py
  tests/integration/testlib/statelib.py
  tests/lib/state_test.py
  tests/lib/validator_test.py
Labels: Wait_Review

#928 test: Fix the memory leak test
  tests/integration/mem_leak_test.py
Labels: Low priority, Wait_Review

#931 test: Add two bond test cases to tier1
  tests/integration/bond_test.py
Labels: Low priority, Wait_Review

#930 integ: add MAC behaviour tests for linux bonds
  tests/integration/bond_test.py
Labels: backport candidate

#933 [nmstate-0.2] integ: add MAC behaviour tests for linux bonds
  tests/integration/bond_test.py
Labels: Wait_Review

#926 Add --version and nmstatectl version
  nmstatectl/nmstatectl.py
  tests/integration/nmstatectl_test.py
Labels: backport candidate

#961 CI container: Changed back to docker.io
  automation/README.md
  automation/run-tests.sh
  packaging/README-container-registry.md
  packaging/README-dockerhub.md
  packaging/build-container.sh
Labels: Wait_Review

#962 test ovs: Remove the dependency of `libnmstate.nm`
  tests/integration/ovs_test.py
  tests/integration/testlib/nmlib.py
  tests/integration/testlib/ovslib.py
Labels: Wait_Review

#968 nm ethernet: Convert mac address from sysfs to upper case
  libnmstate/nm/wired.py
Labels: Wait_Review

#923 automation: Add travis job to run vdsm tests
  .travis.yml
  automation/run-tests.sh
Labels: Wait_Review

#882 linux bridge, vlan filtering: add integ tests
  tests/integration/linux_bridge_test.py
  tests/integration/testlib/bridgelib.py
Labels: Waiting_Rebase

#970 test: Create a empty network state before test starts
  tests/integration/conftest.py
Labels: Wait_Review

#966 tests, integ: split tier1 integration tests
  .travis.yml
  automation/README.md
  automation/run-tests.sh
  tests/integration/conftest.py
Labels: backport candidate

#893 Activate port vlan functionality
  libnmstate/nm/applier.py
  libnmstate/nm/bridge.py
  libnmstate/validator.py
  tests/integration/linux_bridge_test.py
  tests/integration/nm/linux_bridge_test.py
Labels: backport candidate

#973 nm.dns: report nameservers only once
  libnmstate/nm/dns.py
  tests/lib/nm/dns_test.py
Labels: backport candidate

#965 validator: raise if the necessary services are not running
  libnmstate/appliers/ovs_bridge.py
  libnmstate/netinfo.py
  libnmstate/validator.py
  tests/integration/ovs_test.py
  tests/integration/testlib/servicelib.py
Labels: backport candidate

#983 tests, integ: remove team tests xfails
  tests/integration/team_test.py
Labels: Wait_Review

#981 dns: Enable support of 3+ unmixed DNS name server
  libnmstate/validator.py
  tests/integration/dns_test.py
Labels: High priority, Wait_Review

#984 nm team: Only show supported properties
  libnmstate/nm/team.py
Labels: Wait_Review

#985 [nmstate-0.2] dns: Enable support of 3+ unmixed DNS name server
  libnmstate/validator.py
  tests/integration/dns_test.py
Labels: High priority

#989 doc: Update manpage with version argument and command
  doc/nmstatectl.8.in
Labels: backport candidate

#982 team: Sort team ports before verifying
  libnmstate/state.py
  tests/integration/team_test.py
Labels: Waiting_Rebase

#993 state: allow missing arp_ip_target when ARP monitoring disabled
  libnmstate/appliers/bond.py
  libnmstate/state.py
  tests/integration/bond_test.py
  tests/integration/testlib/assertlib.py
Labels: High priority, Work_Ongoing, backport candidate

#992 CHANGELOG: Update change log for 0.2.9 release
  CHANGELOG
Labels: Wait_Review

#996 [nmstate-0.2] VERSION: Bump to 0.2.10
  libnmstate/VERSION
Labels: Wait_Review

#997 tests, integ: fix TypeError on dns tests
  tests/integration/dns_test.py
Labels: Wait_Review

#998 [nmstate-0.2] tests, integ: fix TypeError on dns tests
  tests/integration/dns_test.py
Labels: Wait_Review

#953 nmstatectl: allow route rule filtering by interface
  nmstatectl/nmstatectl.py
  tests/ctl/nmstatectl_test.py
Labels: Waiting_Rebase

#1005 [nmstate-0.2] test, integ: clean auto_dns and auto_routes before tests
  tests/integration/conftest.py
Labels: Wait_Review
