Repository nmstate/nmstate, pull requests merged in 2020-04, with the labels that each got.

#999 bond: Don't merge bond options when bond mode changed
  libnmstate/appliers/bond.py
  libnmstate/metadata.py
  libnmstate/nm/applier.py
  libnmstate/state.py
  tests/integration/bond_test.py
  tests/lib/appliers/bond_test.py
Labels: High priority, Wait_Review

#1012 automation: export /var/log/openvswitch/ovsdb-server.log
  automation/run-tests.sh
Labels: Wait_Review, backport candidate

#878 validator: Check IP config in bond slaves.
  libnmstate/validator.py
  tests/integration/bond_test.py
  tests/integration/linux_bridge_test.py
  tests/integration/ovs_test.py
  tests/integration/team_test.py
  tests/lib/validator_test.py
Labels: Wait_Review, Waiting_Rebase

#1026 CHANGELOG: Release 0.2.10-rc1
  CHANGELOG
Labels: Wait_Review

#1022 Include maintainers' gpg public keys
  README.install.md
  nmstate.gpg
  packaging/README.release.md
Labels: Low priority, Work_Ongoing

#1034 travis: switch to docker as podman 1.9.0 is broken in Ubuntu
  .travis.yml
Labels: Highest priority, Wait_Review

#1036 [nmstate-0.2] travis: switch to docker as podman 1.9.0 is broken in Ubuntu
  .travis.yml
Labels: Highest priority, Wait_Review

#1032 CHANGELOG: New release 0.2.10
  CHANGELOG
Labels: Wait_Review

#1018 nm bond: Fix the bond default option getter
  libnmstate/nm/bond.py
  tests/integration/bond_test.py
Labels: High priority

#1030 validator: Raises warning if interfaces exceeds 1000 in single desire state
  README.md
  doc/nmstatectl.8.in
  libnmstate/validator.py
Labels: Wait_on_submitter

#1000 Route rule: support host without prefix length
  libnmstate/state.py
  tests/integration/route_test.py
  tests/integration/testlib/iprule.py
Labels: Low priority, Wait_Review

#1027 [nmstate-0.2] nmstate.gpg: Include maintainers' gpg public keys
  README.install.md
  nmstate.gpg
  packaging/README.release.md
Labels: Wait_Review

#1051 nm vxlan: Remove unused code nm_version()
  libnmstate/nm/nmclient.py
  libnmstate/nm/vxlan.py
  tests/integration/nm/vxlan_test.py
Labels: Wait_Review

#1050 nm ovs: Remove unused function get_bridge_info()
  libnmstate/nm/ovs.py
  tests/integration/nm/ovs_test.py
Labels: Wait_Review

#1029 sriov: normalize vf mac address before verification
  libnmstate/appliers/sriov.py
  libnmstate/nm/sriov.py
  libnmstate/state.py
  tests/integration/sriov_test.py
Labels: Wait_Review

#1054 schema: New class Bridge be parent of LinuxBridge and OVSBridge
  libnmstate/schema.py
Labels: Wait_Review
