Repository nmstate/nmstate, pull requests merged in 2020-09, with the labels that each got.

#1311 nm/active_connection: Fix timeout in deactivation
  libnmstate/nm/active_connection.py
  tests/integration/timeout_test.py
Labels: Wait_Review

#1312 nm/profile: Fix profile deletion on virtual interface
  libnmstate/nm/profile.py
  tests/integration/nm/profile_test.py
Labels: Wait_Review

#1316 packaging: make varlink as hard requirement
  packaging/nmstate.spec
  requirements.txt
Labels: Wait_Review

#1319 Nispor: Sync with nispor 0.5.0 API changes
  libnmstate/nispor/plugin.py
  requirements.txt
Labels: Wait_Review

#1324 vlan, vxlan: iface cannot have ip when subordinated
  libnmstate/ifaces/vlan.py
  libnmstate/ifaces/vxlan.py
  tests/lib/ifaces/vlan_iface_test.py
  tests/lib/ifaces/vxlan_iface_test.py
Labels: Wait_Review

#1323 schema: fix ethernet operational schema and validation tests
  libnmstate/schemas/operational-state.yaml
  tests/lib/schema_validation_test.py
Labels: Waiting_Rebase, needs_backporting

#1314 SR-IOV: support querying state from Nispor
  libnmstate/nispor/ethernet.py
  libnmstate/nm/sriov.py
  libnmstate/nm/wired.py
Labels: Waiting_Rebase

#1325 nm checkpoint: Clean up even checkpoint rollback/destroy failed
  libnmstate/nm/checkpoint.py
Labels: Wait_Review, needs_backporting

#1322 CONTRIBUTING: add information about git and code structure
  CONTRIBUTING.md
  libnmstate/README.md
Labels: Wait_Review

#1329 route: Sort on metric and next_hop_address also
  libnmstate/route.py
  tests/lib/route_test.py
Labels: Backport_Candicate, Waiting_Rebase

#1327 [Regression] nm bridge: Don't reset bridge options for empty bridge options
  libnmstate/nm/profile.py
  tests/integration/linux_bridge_test.py
  tests/integration/testlib/assertlib.py
Labels: Highest priority, Waiting_Rebase

#1298 state: support `state:ignore`
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/ifaces.py
  libnmstate/nm/profile.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  tests/integration/linux_bridge_test.py
  tests/lib/ifaces_test.py
Labels: New Feature, QE_Approved, Wait_Consumer_QE

#1326 nm.translator: use constants from the schema
  libnmstate/nm/translator.py
  tests/lib/nm/translator_test.py
Labels: Waiting_Rebase

#1340 Fix typo at installing the libvarlink-util package
  nmstatectl/README.varlink.md
Labels: Wait_on_submitter

#1320 nm route: Add support of multiple gateways
  libnmstate/nm/route.py
  tests/integration/route_test.py
  tests/lib/nm/route_test.py
Labels: New Feature, Wait_Consumer_QE, Wait_QE

#1334 nm/device: Use async way for setting device as managed
  libnmstate/nm/device.py
  libnmstate/nm/profile.py
Labels: Waiting_Rebase

#1337 route: Use nispor for running routes
  libnmstate/nispor/plugin.py
  libnmstate/nispor/route.py
  libnmstate/nm/ipv4.py
  libnmstate/nm/ipv6.py
  libnmstate/nm/plugin.py
  libnmstate/nm/route.py
  libnmstate/nmstate.py
  requirements.txt
  tests/integration/plugin_test.py
Labels: Waiting_Rebase

#1330 inclusive language: deprecate "slaves" from the API
  examples/bond_linuxbridge_vlan_up.yml
  examples/ovsbridge_bond_create.yml
  libnmstate/ifaces/bond.py
  libnmstate/ifaces/ovs.py
  libnmstate/nm/bond.py
  libnmstate/nm/ovs.py
  libnmstate/nm/translator.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  tests/integration/bond_test.py
  tests/integration/nm/bond_test.py
  tests/integration/nm/iproute_config_test.py
  tests/integration/nm/ovs_test.py
  tests/integration/ovs_test.py
  tests/integration/testlib/bondlib.py
  tests/integration/testlib/ovslib.py
  tests/integration/testlib/statelib.py
  tests/lib/ifaces/bond_iface_test.py
  tests/lib/ifaces/ovs_iface_test.py
  tests/lib/ifaces_test.py
  tests/lib/netapplier_test.py
  tests/lib/nm/translator_test.py
  tests/lib/schema_deprecation_test.py
  tests/lib/schema_validation_test.py
Labels: Waiting_Rebase

#1349 schema: fix flake8 warning on unnecessary f-string
  libnmstate/schema.py
Labels: Waiting_Rebase

#1341 nm/bond: Keep child interface when bond mode change
  libnmstate/nm/profile.py
  tests/integration/bond_test.py
Labels: Waiting_Rebase

#1310 vrf: Add support of Virtual Routing and Forwarding
  examples/vrf0_absent.yml
  examples/vrf0_with_eth1.yml
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/vrf.py
  libnmstate/nispor/plugin.py
  libnmstate/nispor/vrf.py
  libnmstate/nm/profile.py
  libnmstate/nm/translator.py
  libnmstate/nm/vrf.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  tests/integration/examples_test.py
  tests/integration/vrf_test.py
  tests/lib/ifaces/vrf_iface_test.py
  tests/lib/nm/translator_test.py
  tests/lib/schema_validation_test.py
Labels: New Feature, QE_Approved, Wait_Consumer_QE

#1356 tests: fix bad variable names in loops
  libnmstate/ifaces/ovs.py
  tests/integration/nm/ovs_test.py
  tests/integration/team_test.py
Labels: Wait_Review

#1357 nm: Change NetworkManager plugin as optional
  libnmstate/nm/common.py
  libnmstate/nm/plugin.py
  libnmstate/nmstate.py
  tests/integration/plugin_test.py
Labels: Wait_Review
