Repository nmstate/nmstate, pull requests merged in 2020-06, with the labels that each got.

#1089 nm.active_connection: fix incorrect use of GLib.Error
  libnmstate/nm/active_connection.py
  tests/lib/nm/active_connection_test.py
Labels: Waiting_Rebase

#1099 dns: Fix DNS metadata generation
  libnmstate/dns.py
Labels: Wait_Review

#1100 nm/active_connection: Wait for device been fully deactivated
  libnmstate/nm/active_connection.py
Labels: Wait_Review

#1101 nm/route: Skip query on ActiveConnection without interface name
  libnmstate/nm/route.py
Labels: Wait_Review

#1103 nm/connection: Wait on rollback
  libnmstate/nm/checkpoint.py
  libnmstate/nm/connection.py
Labels: Wait_Review

#1024 state: Differentiate DOWN and ABSENT state
  libnmstate/ifaces/ifaces.py
  libnmstate/nm/applier.py
  tests/integration/dynamic_ip_test.py
  tests/integration/profile_test.py
  tests/integration/testlib/ifacelib.py
Labels: Wait_Review

#1085 [Plugin design] checkpoint: Move checkpoint functions to plugin level
  libnmstate/netapplier.py
  libnmstate/nm/checkpoint.py
  libnmstate/nm/plugin.py
  libnmstate/nmstate.py
  tests/integration/nm/checkpoint.py
  tests/integration/nm/conftest.py
  tests/lib/netapplier_test.py
Labels: Wait_Review

#1088 [Plugin design] validator: Remove the use of nm module
  libnmstate/nm/applier.py
  libnmstate/nm/ovs.py
  libnmstate/nm/plugin.py
  libnmstate/nm/team.py
  libnmstate/plugin.py
  libnmstate/validator.py
  tests/integration/nm/ovs_test.py
Labels: Wait_Review

#1111 nm/checkpoint: Handle NULL NM.Device when rollback
  libnmstate/nm/checkpoint.py
Labels: Wait_Review

#1110 ovs db plugin: add support of external_ids
  libnmstate/ifaces/ovs.py
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  packaging/Dockerfile.centos8-nmstate-dev
  packaging/Dockerfile.fedora-nmstate-dev
  packaging/nmstate.spec
  tests/integration/ovs_test.py
  tests/integration/testlib/assertlib.py
  tests/integration/testlib/ovslib.py
Labels: Wait_Other_PR, Wait_on_submitter

#1109 linux bridge: Add linux bridge options required by oVirt
  libnmstate/ifaces/bridge.py
  libnmstate/nm/applier.py
  libnmstate/nm/bridge.py
  libnmstate/nm/common.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  tests/integration/linux_bridge_test.py
  tests/integration/nm/linux_bridge_test.py
  tests/integration/testlib/env.py
Labels: Wait_Review

#1008 nm.ovs: OVS Patch support
  examples/ovsbridge_patch_create.yml
  examples/ovsbridge_patch_delete.yml
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/ovs.py
  libnmstate/nm/applier.py
  libnmstate/nm/ovs.py
  libnmstate/nm/plugin.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  tests/integration/examples_test.py
  tests/integration/nm/ovs_test.py
  tests/integration/ovs_test.py
  tests/integration/testlib/env.py
  tests/integration/testlib/ovslib.py
  tests/lib/schema_validation_test.py
Labels: Wait_Review

#1114 libnmstate: Implement non persistent state support
  doc/nmstatectl.8.in
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/bond.py
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/ovs.py
  libnmstate/net_state.py
  libnmstate/netapplier.py
  libnmstate/nm/applier.py
  libnmstate/nm/connection.py
  libnmstate/nm/plugin.py
  libnmstate/plugin.py
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  nmstatectl/nmstatectl.py
  tests/ctl/nmstatectl_test.py
  tests/integration/profile_test.py
  tests/integration/vlan_test.py
  tests/lib/netapplier_test.py
Labels: Wait_Review

#1141 tests: update outdated xfails
  tests/integration/dynamic_ip_test.py
  tests/integration/iface_admin_state_test.py
  tests/integration/route_test.py
  tests/integration/vxlan_test.py
  tests/lib/nm/route_test.py
Labels: Wait_Review, backport candidate

#1128 test: Add OVS internal interface MTU modification test
  tests/integration/ovs_test.py
  tests/integration/testlib/ovslib.py
Labels: Waiting_Rebase

#1137 test: Register pytest marker
  tests/integration/conftest.py
Labels: Waiting_Rebase

#1127 ip: canonicalize IP address
  libnmstate/ifaces/base_iface.py
  libnmstate/iplib.py
  libnmstate/route.py
  libnmstate/route_rule.py
  tests/lib/route_rule_test.py
Labels: Waiting_Rebase, backport candidate

#1142 nm.ipv4, nm.ipv6: add auto-route-table-id support for IPv4 and IPv6
  libnmstate/nm/ipv4.py
  libnmstate/nm/ipv6.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  tests/integration/dynamic_ip_test.py
  tests/integration/nm/ipv4_test.py
Labels: 0.4 next, New Feature

#1148 base_iface: rename iface_type property to type
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/ovs.py
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  tests/lib/ifaces/ovs_iface_test.py
Labels: Waiting_Rebase

#1149 [nmstate-0.3] tests: update outdated xfails
  tests/integration/dynamic_ip_test.py
  tests/integration/iface_admin_state_test.py
  tests/integration/route_test.py
  tests/integration/vxlan_test.py
  tests/lib/nm/route_test.py
Labels: Wait_Review

#1151 ovs: Eliminate the repeat call of is_ovs_running()
  libnmstate/nm/plugin.py
  libnmstate/validator.py
Labels: High priority, backport candidate

#1152 nm/checkpoint: Register async action before invoke the async action
  libnmstate/nm/checkpoint.py
Labels: Waiting_Rebase, backport candidate

#1145 ifaces: validate unknown type ifaces in desired and current state
  libnmstate/ifaces/ifaces.py
  tests/lib/ifaces_test.py
Labels: backport candidate

#1160 [nmstate-0.3] ifaces: ignore unknown type ifaces from current and desired state
  libnmstate/ifaces/ifaces.py
  tests/lib/ifaces_test.py
Labels: Wait_Review

#1163 nmstatectl: Fix the support of multiple state files
  nmstatectl/nmstatectl.py
  tests/integration/nmstatectl_test.py
Labels: High priority

#1159 nm/device: Only invoke reapply on activated device
  libnmstate/nm/device.py
Labels: backport candidate

#1143 nm ip: Use running config for DHCP status
  libnmstate/nm/ipv4.py
  libnmstate/nm/ipv6.py
  libnmstate/nm/plugin.py
  libnmstate/nm/profile.py
  tests/integration/nm/ipv4_test.py
  tests/lib/nm/ipv4_test.py
  tests/lib/nm/ipv6_test.py
Labels: Waiting_Rebase

#1168 [nmstate-0.3] nmstatectl: Fix the support of multiple state files
  nmstatectl/nmstatectl.py
  tests/integration/nmstatectl_test.py
Labels: Waiting_Rebase

#1162 nm/ovs: Sort the OVS interface and OVS bond ports.
  libnmstate/nm/ovs.py
  tests/integration/ovs_test.py
  tests/integration/testlib/statelib.py
Labels: Waiting_Rebase, backport candidate

#1169 [nmstate-0.3] nm/device: Only invoke reapply on activated device
  libnmstate/nm/device.py
Labels: Waiting_Rebase

#1164 dns: Fix remove dns config
  libnmstate/dns.py
  tests/integration/dns_test.py
  tests/lib/dns_test.py
Labels: Highest priority, Wait_Review, backport candidate

#1125 pretty state: Dumping state in the sorted order with priority
  libnmstate/prettystate.py
  tests/integration/linux_bridge_test.py
  tests/integration/nmstatectl_test.py
  tests/integration/ovs_test.py
  tests/lib/pretty_state.py
Labels: Wait_Review, backport candidate

#1170 [nmstate-0.3] nm/ovs: Sort the OVS interface and OVS bond ports.
  libnmstate/nm/ovs.py
  tests/integration/ovs_test.py
  tests/integration/testlib/statelib.py
Labels: Wait_Review
