Repository nmstate/nmstate, pull requests merged in 2020-08, with the labels that each got.

#1257 automation: Fail vdsm suite on first error
  automation/tests-container-utils.sh
Labels: Wait_Review, backport candidate

#1255 ovs: Fix bug when adding bond to existing bridge
  libnmstate/ifaces/ifaces.py
  tests/integration/ovs_test.py
Labels: Wait_Review, backport candidate

#1258 [nmstate-0.3] ovs: Fix bug when adding bond to existing bridge
  libnmstate/ifaces/ifaces.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#1256 nm: Fix converting memory-only profile to persistent
  libnmstate/nm/applier.py
  libnmstate/nm/connection.py
  tests/integration/nm/profile_test.py
Labels: Wait_Review, backport candidate

#1259 [nmstate-0.3] nm: Fix converting memory-only profile to persistent
  libnmstate/nm/applier.py
  libnmstate/nm/connection.py
  tests/integration/nm/profile_test.py
Labels: Wait_Review

#1264 tox: Fix pylint test
  tox.ini
Labels: Highest priority, Wait_Review

#1263 [nmstate-0.3] tox: Fix pylint test
  tox.ini
Labels: Highest priority, Wait_Review

#1262 ovsdb: Preserve the NM external_ids of newly created interface
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#1266 [nmstate-0.3] ovsdb: Preserve the NM external_ids
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#1267 tests: add test changing multicast-snooping from false to true
  tests/integration/linux_bridge_test.py
  tests/integration/testlib/env.py
Labels: Wait_Review

#1268 [nmstate-0.3] tests: add test changing multicast-snooping from false to true
  tests/integration/linux_bridge_test.py
  tests/integration/testlib/env.py
Labels: Wait_Review

#1273 docs: clean up documentation
  README.debug.md
  README.install.md
  README.md
  commit-template.txt
Labels: Wait_Review

#1278 test: Enable IPv6 in container globally
  automation/tests-container-utils.sh
  tests/integration/dynamic_ip_test.py
Labels: Wait_Review, backport candidate

#1280 [nmstate-0.3] test: Enable IPv6 in container globally
  automation/tests-container-utils.sh
  tests/integration/dynamic_ip_test.py
Labels: Wait_Review

#1281 [nmstate-0.3] automation: Fail vdsm suite on first error
  automation/tests-container-utils.sh
Labels: Wait_Review

#1283 ovsdb: Allowing remove all ports from OVS bridge
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  tests/integration/ovs_test.py
Labels: Wait_Review, backport candidate

#1275 nispor: Introduce nispor plugin
  libnmstate/nispor/__init__.py
  libnmstate/nispor/base_iface.py
  libnmstate/nispor/bond.py
  libnmstate/nispor/bridge.py
  libnmstate/nispor/dummy.py
  libnmstate/nispor/ethernet.py
  libnmstate/nispor/plugin.py
  libnmstate/nispor/vlan.py
  libnmstate/nispor/vxlan.py
  libnmstate/nm/ipv4.py
  libnmstate/nm/ipv6.py
  libnmstate/nm/plugin.py
  libnmstate/nm/profile.py
  libnmstate/nm/wired.py
  libnmstate/nmstate.py
  packaging/Dockerfile.centos-stream-nmstate-dev
  packaging/Dockerfile.centos8-nmstate-dev
  packaging/Dockerfile.fedora-nmstate-dev
  packaging/nmstate.spec
  tests/integration/dynamic_ip_test.py
  tests/integration/linux_bridge_test.py
  tests/integration/nm/ipv4_test.py
  tests/integration/nm/linux_bridge_test.py
  tests/integration/nm/ovs_test.py
  tests/integration/nm/wired_test.py
  tests/integration/nmstatectl_test.py
  tests/integration/static_ip_address_test.py
  tests/integration/testlib/assertlib.py
  tests/integration/testlib/dummy.py
  tests/integration/testlib/ifacelib.py
  tests/lib/nm/ipv4_test.py
  tests/lib/nm/ipv6_test.py
  tests/lib/nm/wired_test.py
Labels: New Feature, Wait_Review

#1285 [nmstate-0.3] ovsdb: Allowing remove all ports from OVS bridge
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#1270 libnmstate-varlink: Implementing varlink support for libnmstate
  nmstatectl/README.varlink.md
  nmstatectl/io.nmstate.varlink
  nmstatectl/nmstate_varlink.py
  nmstatectl/nmstatectl.py
  packaging/Dockerfile.centos-stream-nmstate-dev
  packaging/Dockerfile.centos8-nmstate-dev
  packaging/Dockerfile.fedora-nmstate-dev
  packaging/nmstate.spec
  setup.py
  tests/integration/varlink_service_test.py
Labels: Wait_on_submitter

#1293 route_rule: fix adding route rule using auto_route_table_id
  libnmstate/ifaces/ifaces.py
  libnmstate/route_rule.py
  tests/integration/route_test.py
Labels: Wait_Review

#1272 nmstatectl: filter route rule against auto-route-table-id
  nmstatectl/nmstatectl.py
Labels: Wait_Review

#1294 python: Instruct black to use python 3.6 style
  pyproject.toml
Labels: Waiting_Rebase

#1295 inclusive language: clean up master branch removal leftovers
  README.md
  automation/README.md
  automation/tests-container-utils.sh
  packaging/README-dockerhub.md
Labels: Wait_Review

#1306 CHANGELOG: Update changelog for 0.3.5 release
  CHANGELOG
Labels: Wait_Review

#1307 CHANGELOG: Amend the 0.3.4 changelog
  CHANGELOG
Labels: Wait_Review

#1304 CHANGELOG: Update changelog for 0.4.0 release
  CHANGELOG
Labels: Wait_Review

#1308 [nmstate-0.3] VERSION: Bump to 0.3.6
  libnmstate/VERSION
Labels: Wait_Review

#1309 VERSION: Bump to 0.4.1
  libnmstate/VERSION
Labels: Wait_Review

#1282 profile: rewrite NM profile activation
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/ovs.py
  libnmstate/nm/__init__.py
  libnmstate/nm/applier.py
  libnmstate/nm/checkpoint.py
  libnmstate/nm/connection.py
  libnmstate/nm/device.py
  libnmstate/nm/lldp.py
  libnmstate/nm/ovs.py
  libnmstate/nm/plugin.py
  libnmstate/nm/profile.py
  libnmstate/nm/profile_state.py
  libnmstate/nm/sriov.py
  libnmstate/nm/team.py
  libnmstate/nm/user.py
  libnmstate/nm/vxlan.py
  tests/integration/nm/bond_test.py
  tests/integration/nm/ipv4_test.py
  tests/integration/nm/linux_bridge_test.py
  tests/integration/nm/ovs_test.py
  tests/integration/nm/route_rule_test.py
  tests/integration/nm/vlan_test.py
  tests/integration/nm/vxlan_test.py
  tests/integration/nm/wired_test.py
  tests/integration/testlib/vxlan.py
  tests/integration/vxlan_test.py
  tests/lib/nm/connection_test.py
  tests/lib/nm/device_test.py
  tests/lib/nm/dns_test.py
  tests/lib/nm/ovs_test.py
  tests/lib/nm/route_test.py
Labels: Waiting_Rebase
