Repository nmstate/nmstate, pull requests merged in 2020-12, with the labels that each got.

#1437 ifaces: do not remove unmanaged orphan interfaces
  libnmstate/ifaces/ifaces.py
  tests/integration/ovs_test.py
Labels: Highest priority, Wait_Review

#1438 [nmstate-0.3] ifaces: do not remove unmanaged orphan interfaces
  libnmstate/ifaces/ifaces.py
  tests/integration/ovs_test.py
Labels: Highest priority, Wait_Review

#1440 VERSION: Bump to 1.0.1
  libnmstate/VERSION
Labels: Wait_Review

#1436 nm ovs: Sort the OVS port order by its name
  libnmstate/nm/ovs.py
Labels: Waiting_Rebase

#1443 varlink: Fix the logger
  nmstatectl/nmstate_varlink.py
Labels: Wait_Review

#1445 ovsdb: Allowing change external_ids of OVS system interfaces
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/ovs.py
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#1449 [nmstate-0.3] nm route: Add support of multiple gateways
  libnmstate/nm/route.py
  tests/integration/route_test.py
  tests/lib/nm/route_test.py
Labels: Waiting_Rebase

#1446 ovs: Raise NmstateValueError when desired interface is orphan
  libnmstate/ifaces/ifaces.py
  tests/integration/ovs_test.py
Labels: Waiting_Rebase

#1448 linux bridge: Allowing mixed case for group address
  libnmstate/ifaces/linux_bridge.py
  tests/integration/linux_bridge_test.py
  tests/integration/testlib/statelib.py
Labels: Waiting_Rebase

#1447 iface:: No need to validate absent interfaces
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/bridge.py
  libnmstate/ifaces/infiniband.py
  libnmstate/ifaces/linux_bridge.py
  libnmstate/ifaces/macvlan.py
  libnmstate/ifaces/ovs.py
  libnmstate/ifaces/vlan.py
  libnmstate/ifaces/vxlan.py
  tests/integration/static_ip_address_test.py
Labels: Wait_Review

#1451 test ovs: NM 1.29+ support memory OVS profiles now
  tests/integration/ovs_test.py
  tests/integration/testlib/env.py
Labels: Wait_Review

#1419 query: new function for showing running config
  doc/nmstatectl.8.in
  libnmstate/__init__.py
  libnmstate/netinfo.py
  libnmstate/nispor/base_iface.py
  libnmstate/nispor/bond.py
  libnmstate/nispor/bridge.py
  libnmstate/nispor/ethernet.py
  libnmstate/nispor/macvlan.py
  libnmstate/nispor/macvtap.py
  libnmstate/nispor/plugin.py
  libnmstate/nispor/vlan.py
  libnmstate/nispor/vrf.py
  libnmstate/nispor/vxlan.py
  libnmstate/nm/plugin.py
  libnmstate/nmstate.py
  libnmstate/plugin.py
  nmstatectl/io.nmstate.varlink
  nmstatectl/nmstate_varlink.py
  nmstatectl/nmstatectl.py
  tests/integration/dynamic_ip_test.py
  tests/integration/lldp_test.py
  tests/integration/varlink_service_test.py
Labels: New Feature, Wait_Consumer_QE, Wait_QE, Waiting_Rebase
