Repository nmstate/nmstate, pull requests merged in 2020-07, with the labels that each got.

#1176 [Regression] nm: Only create ethernet section when desired
  libnmstate/nm/applier.py
  tests/integration/bond_test.py
Labels: Highest priority, Waiting_Rebase, backport candidate

#980 test nm: linux bridge worker interface should lose IP address
  tests/integration/nm/linux_bridge_test.py
Labels: Wait_Review, backport candidate

#1178 [nmstate-0.3] nm: Only create ethernet section when desired
  libnmstate/nm/applier.py
  tests/integration/bond_test.py
Labels: Highest priority, Wait_Review

#1179 [nmstate-0.3] test nm: linux bridge worker interface should lose IP address
  tests/integration/nm/linux_bridge_test.py
Labels: Wait_Review

#1183 nmstate.gpg: Add gpg key of maintainer Fernando Fernandez Mancera
  nmstate.gpg
Labels: Waiting_Rebase

#1185 CONTRIBUTING: fix information about tracking issues in Nmstate
  CONTRIBUTING.md
Labels: Wait_Review

#1188 dns: fix remove dns config
  libnmstate/dns.py
  tests/integration/dns_test.py
Labels: Highest priority, Waiting_Rebase, backport candidate

#1189 [nmstate-0.3] dns: fix remove dns config
  libnmstate/dns.py
  tests/integration/dns_test.py
Labels: Wait_Review

#1053 automation: allow to run the tests out of the container
  automation/run-tests.sh
  automation/tests-container-utils.sh
  automation/tests-machine-utils.sh
  tests/integration/lldp_test.py
Labels: Wait_Review

#1177 travis: add job testing tier1 tests with openvswitch2.13
  .travis.yml
  automation/run-tests.sh
  automation/tests-container-utils.sh
Labels: Wait_on_submitter

#1196 automation: fix --debug-shell argument
  automation/tests-container-utils.sh
Labels: Wait_Review

#1198 automation: extend --customize argument for no container support
  automation/run-tests.sh
  automation/tests-container-utils.sh
Labels: Wait_Review

#1202 nm/checkpoint: Fix the logging of checkpoint creation
  libnmstate/nm/checkpoint.py
Labels: Waiting_Rebase

#1217 linux bridge: Workaround for 250 HZ kernel
  libnmstate/error.py
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/linux_bridge.py
  tests/integration/linux_bridge_test.py
  tests/integration/nm/linux_bridge_test.py
  tests/integration/testlib/env.py
Labels: Wait_Review, backport candidate

#1218 [nmstate-0.3] linux bridge: Workaround for 250 HZ kernel
  libnmstate/error.py
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/linux_bridge.py
  tests/integration/linux_bridge_test.py
  tests/integration/nm/linux_bridge_test.py
  tests/integration/testlib/env.py
Labels: Wait_Review

#1210 nm: Increase the minimum NetworkManager to 1.26.0
  .travis.yml
  libnmstate/nm/bridge.py
  libnmstate/nm/common.py
  packaging/Dockerfile.centos8-nmstate-dev
  packaging/Dockerfile.fedora-nmstate-dev
  packaging/nmstate.spec
  tests/integration/examples_test.py
  tests/integration/linux_bridge_test.py
  tests/integration/nm/linux_bridge_test.py
  tests/integration/ovs_test.py
  tests/integration/testlib/env.py
Labels: Wait_Review, backport candidate

#1227 sriov: raise proper exception when SR-IOV parameter is not supported
  libnmstate/nm/connection.py
Labels: Wait_Review, backport candidate

#1231 [Regression] Ifaces: allowing child been removed
  libnmstate/ifaces/ifaces.py
Labels: Highest priority, backport candidate

#1230 iface: Allowing moving subordinate from absent interface
  libnmstate/ifaces/ifaces.py
  tests/integration/linux_bridge_test.py
Labels: backport candidate

#1221 Packaging: adjust dependecy requirements #1203
  packaging/nmstate.spec
Labels: Wait_on_submitter

#1222 [nmstate-0.3] nm: Increase the minimum NetworkManager to 1.26.0
  .travis.yml
  libnmstate/nm/bridge.py
  libnmstate/nm/common.py
  packaging/Dockerfile.centos8-nmstate-dev
  packaging/Dockerfile.fedora-nmstate-dev
  packaging/nmstate.spec
  tests/integration/examples_test.py
  tests/integration/linux_bridge_test.py
  tests/integration/nm/linux_bridge_test.py
  tests/integration/ovs_test.py
  tests/integration/testlib/env.py
Labels: Wait_Review

#1056 Integrate CentOS-stream into CI
  .travis.yml
  automation/run-tests.sh
  automation/tests-container-utils.sh
  packaging/Dockerfile.centos-stream-nmstate-dev
  packaging/build-container.sh
Labels: Wait_on_submitter

#1232 [nmstate-0.3] Ifaces: allowing child been removed
  libnmstate/ifaces/ifaces.py
Labels: Highest priority, Waiting_Rebase

#1229 test: Isolate veth peer into separate net namespace
  automation/run-tests.sh
  tests/integration/dynamic_ip_test.py
  tests/integration/lldp_test.py
  tests/integration/testlib/veth.py
Labels: Waiting_Rebase, backport candidate

#1233 [nmstate-0.3] iface: Allowing moving subordinate from absent interface
  libnmstate/ifaces/ifaces.py
  tests/integration/linux_bridge_test.py
Labels: Waiting_Rebase

#1234 [nmstate-0.3] sriov: raise proper exception when SR-IOV parameter is not supported
  libnmstate/nm/connection.py
Labels: Waiting_Rebase

#1226 state: Don't merge state:down if not defined in desire state
  libnmstate/ifaces/base_iface.py
  tests/lib/ifaces/base_iface_test.py
Labels: backport candidate

#1228 [nmstate-0.3] test: Mark test_ovs_remove_port as xfail
  tests/integration/ovs_test.py
Labels: Waiting_Rebase

#1220 nm bridge: Support replacing unmanaged ports
  libnmstate/nm/applier.py
  tests/integration/linux_bridge_test.py
Labels: backport candidate

#1236 [nmstate-0.3] state: Don't merge state:down if not defined in desire state
  libnmstate/ifaces/base_iface.py
  tests/lib/ifaces/base_iface_test.py
Labels: Wait_Review

#1235 [nmstate-0.3] test: Isolate veth peer into separate net namespace
  automation/run-tests.sh
  tests/integration/dynamic_ip_test.py
  tests/integration/lldp_test.py
  tests/integration/testlib/veth.py
Labels: Wait_Review

#1237 [nmstate-0.3] nm bridge: Support replacing unmanaged ports
  libnmstate/nm/applier.py
  tests/integration/linux_bridge_test.py
Labels: Wait_Review

#1238 CHANGELOG: Update changelog for 0.3.4 release
  CHANGELOG
Labels: Wait_Review

#1242 nm.wired: do not report MTU if it is 0
  libnmstate/nm/wired.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#1243 [nmstate-0.3] nm.wired: do not report MTU if it is 0
  libnmstate/nm/wired.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#1245 nm ovs: Raise NmstateNotSupportedError for save_to_disk=False
  libnmstate/nm/applier.py
  tests/integration/ovs_test.py
Labels: Wait_Review, backport candidate

#1246 [nmstate-0.3] nm ovs: Raise NmstateNotSupportedError for save_to_disk=False
  libnmstate/nm/applier.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#1247 nm: Mark external subordinate as changed
  libnmstate/nm/applier.py
  tests/integration/nm/iproute_config_test.py
Labels: Wait_Review, backport candidate

#1248 [nmstate-0.3] nm: Mark external subordinate as changed
  libnmstate/nm/applier.py
  tests/integration/nm/iproute_config_test.py
Labels: Wait_Review

#1251 nm profile: Remove inactivate profile of desired interface
  libnmstate/nm/applier.py
  libnmstate/nm/connection.py
  tests/integration/nm/profile_test.py
Labels: Highest priority, Wait_Review

#1252 [nmstate-0.3] nm profile: Remove inactivate profile of desired interface
  libnmstate/nm/applier.py
  libnmstate/nm/connection.py
  tests/integration/nm/profile_test.py
Labels: Wait_Review

#1253 CI: Remove NM copr repo from CentOS stream image
  packaging/Dockerfile.centos-stream-nmstate-dev
Labels: Wait_Review
