Repository nmstate/nmstate, pull requests merged in 2020-11, with the labels that each got.

#1404 [nmstate-0.3] nm.ipv6: call clear_routing_rules() when creating the setting
  libnmstate/nm/ipv6.py
  tests/integration/route_test.py
Labels: Wait_Review

#1408 tox: Upgrade python-black to 20.8b1
  libnmstate/dns.py
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/infiniband.py
  libnmstate/net_state.py
  libnmstate/nm/active_connection.py
  libnmstate/nm/ovs.py
  libnmstate/nm/profile.py
  libnmstate/nm/profile_state.py
  tests/integration/iface_admin_state_test.py
  tests/integration/infiniband_test.py
  tests/integration/linux_bridge_test.py
  tests/integration/nmstatectl_test.py
  tests/integration/ovs_test.py
  tests/integration/sriov_test.py
  tests/integration/varlink_service_test.py
  tests/lib/dns_test.py
  tests/lib/netapplier_test.py
  tests/lib/route_rule_test.py
  tox.ini
Labels: Wait_Review

#1409 route: mark interface as changed on gen_route_state()
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/ifaces.py
  libnmstate/route.py
Labels: Wait_Review

#1412 requirements: nispor 1.0.0 or greater is now required
  libnmstate/nispor/base_iface.py
  libnmstate/nispor/bridge.py
  libnmstate/nispor/plugin.py
  libnmstate/nispor/route.py
  requirements.txt
Labels: Work_Ongoing

#1405 nm: rewrite profile modification code
  libnmstate/nm/__init__.py
  libnmstate/nm/active_connection.py
  libnmstate/nm/checkpoint.py
  libnmstate/nm/connection.py
  libnmstate/nm/context.py
  libnmstate/nm/device.py
  libnmstate/nm/dns.py
  libnmstate/nm/macvlan.py
  libnmstate/nm/ovs.py
  libnmstate/nm/plugin.py
  libnmstate/nm/profile.py
  libnmstate/nm/profile_state.py
  libnmstate/nm/profiles.py
  libnmstate/nm/sriov.py
  tests/integration/dynamic_ip_test.py
  tests/integration/nm/bond_test.py
  tests/integration/nm/ip_test.py
  tests/integration/nm/ipv4_test.py
  tests/integration/nm/linux_bridge_test.py
  tests/integration/nm/ovs_test.py
  tests/integration/nm/profile_test.py
  tests/integration/nm/route_rule_test.py
  tests/integration/nm/vlan_test.py
  tests/integration/nm/vxlan_test.py
  tests/integration/nm/wired_test.py
  tests/integration/ovs_test.py
  tests/integration/static_ip_address_test.py
  tests/lib/nm/connection_test.py
  tests/lib/nm/device_test.py
  tests/lib/nm/dns_test.py
  tests/lib/nm/ovs_test.py
  tests/lib/nm/route_test.py
Labels: Wait_Review

#1410 nispor: gather route rules from nispor
  libnmstate/nispor/plugin.py
  libnmstate/nispor/route_rule.py
  libnmstate/nmstate.py
Labels: Wait_Review

#1415 nispor: Use default mac address when iface does not have
  libnmstate/nispor/base_iface.py
Labels: Highest priority, Wait_Review

#1406 ovs: Support user space only interface
  libnmstate/dns.py
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/bond.py
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/linux_bridge.py
  libnmstate/ifaces/ovs.py
  libnmstate/nm/ovs.py
  libnmstate/nm/profiles.py
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  libnmstate/route.py
  tests/integration/nm/ovs_test.py
  tests/integration/ovs_test.py
  tests/lib/dns_test.py
  tests/lib/ifaces/bond_iface_test.py
  tests/lib/ifaces/infiniband_test.py
  tests/lib/ifaces/linux_bridge_iface_test.py
  tests/lib/ifaces/ovs_iface_test.py
  tests/lib/ifaces/vlan_iface_test.py
  tests/lib/ifaces/vxlan_iface_test.py
  tests/lib/ifaces_test.py
  tests/lib/route_rule_test.py
  tests/lib/route_test.py
Labels: Waiting_Rebase

#1418 route rule: Remove left over codes
  libnmstate/nispor/route_rule.py
  libnmstate/nm/ipv4.py
  libnmstate/nm/ipv6.py
  libnmstate/nm/plugin.py
  libnmstate/nm/route.py
  libnmstate/nmstate.py
Labels: Wait_Review
