Repository nmstate/nmstate, pull requests merged in 2020-02, with the labels that each got.

#735 Travis: Run py36 unit test on CentOS 8 CI image
  .travis.yml
  automation/run-tests.sh
  packaging/Dockerfile.centos8-nmstate-dev
Labels: Waiting_Rebase

#764 metadata: Use schema constants
  libnmstate/metadata.py
Labels: Wait_Review

#757 tox, tavis: remove python 3.7 unit tests
  .travis.yml
  automation/run-tests.sh
  tox.ini
Labels: Wait_Review

#760 tests, integ: Do not run test_nm_ovs_plugin_missing
  tests/integration/ovs_test.py
Labels: Wait_Review

#766 DHCP tests: Do not use the lease database
  tests/integration/dynamic_ip_test.py
Labels: Waiting_Rebase

#600 test ovs-bridge + ovs-interface with same name
  tests/integration/ovs_test.py
Labels: Wait_Review

#787 nm ovs: Fix bug of editing existing OVS interface
  libnmstate/nm/applier.py
  tests/integration/ovs_test.py
Labels: High priority

#794 nm.team: Check if "device" exists before delete it
  libnmstate/nm/team.py
Labels: Wait_Review

#800 team: Fix failure of creating team interface with slaves
  libnmstate/appliers/team.py
  libnmstate/metadata.py
  libnmstate/nm/team.py
  tests/integration/team_test.py
Labels: Wait_Review

#796 libnmstate: Do not remove slaves implicitly with master
  libnmstate/appliers/ovs_bridge.py
  libnmstate/netapplier.py
  libnmstate/state.py
  tests/integration/bond_test.py
  tests/integration/linux_bridge_test.py
  tests/integration/ovs_test.py
  tests/lib/state_test.py
Labels: High priority, Waiting_Rebase, next release

#804 nm, team: Fix reporting of team slaves
  libnmstate/nm/team.py
  tests/integration/team_test.py
Labels: next release

#793 tests: Use schema constants in unit and integration tests
  tests/integration/nm/bond_test.py
  tests/lib/metadata_test.py
  tests/lib/netapplier_test.py
  tests/lib/netinfo_test.py
  tests/lib/nm/applier_test.py
  tests/lib/nm/bond_test.py
  tests/lib/nm/ovs_test.py
  tests/lib/nm/translator_test.py
  tests/lib/schema_validation_test.py
  tests/lib/state_test.py
  tests/lib/validator_test.py
Labels: Wait_Review

#807 nm.team: fetch the slaves using NM.DeviceTeam.get_slaves()
  libnmstate/nm/team.py
  tests/integration/team_test.py
Labels: next release

#635 libnmstate: Deprecate positional arguments to be used for keyword arguments
  libnmstate/deprecation.py
  libnmstate/netapplier.py
  libnmstate/netinfo.py
  tests/lib/netapplier_test.py
  tests/lib/netinfo_test.py
Labels: Waiting_Rebase, next release

#813 CI container: Fix rpmdb corruption
  packaging/Dockerfile.centos8-nmstate-dev
Labels: Wait_Review

#814 automation: Fix failure of building srpm
  MANIFEST.in
Labels: Wait_Review

#776 nm ip: Extend the DHCP/Autoconf timeout to infinity
  libnmstate/nm/ipv4.py
  libnmstate/nm/ipv6.py
  packaging/nmstate.spec
  tests/integration/dynamic_ip_test.py
Labels: High priority, Wait_Other_Response, next release

#819 examples, team: add team interface examples
  examples/team0_absent.yml
  examples/team0_with_slaves.yml
  tests/integration/examples_test.py
Labels: next release

#688 nm/bond: Get in-kernel runtime bond options
  libnmstate/nm/bond.py
  tests/integration/bond_test.py
  tests/integration/nm/bond_test.py
  tests/lib/nm/bond_test.py
Labels: next release

#820 CHANGELOG: update change log for 0.2.5 release
  CHANGELOG
Labels: Wait_Review

#827 bond: Add support of fail_over_mac=active with active backup mode
  libnmstate/appliers/bond.py
  libnmstate/netapplier.py
  libnmstate/nm/applier.py
  libnmstate/nm/bond.py
  libnmstate/validator.py
  tests/integration/bond_test.py
  tests/integration/nm/bond_test.py
  tests/lib/nm/bond_test.py
  tests/lib/validator_test.py
Labels: Wait_Review

#830 travis: Fix run test with copr repo
  automation/run-tests.sh
Labels: Wait_Review

#833 integ: fix missing clean up in vlan integration tests
  tests/integration/vlan_test.py
Labels: Wait_Review, next release

#834 nm, bond: Report only non-default settings
  libnmstate/nm/bond.py
Labels: High priority, Wait_Review, next release

#483 route: Discard routes next hop to DHCP interface
  libnmstate/state.py
  tests/integration/dynamic_ip_test.py
Labels: Medium priority, next release

#836 verification, bond: prepare "arp_ip_target" option for verification
  libnmstate/nm/bond.py
  tests/integration/bond_test.py
Labels: Wait_Review, next release

#824 test: Collect coredump when exists
  automation/run-tests.sh
  automation/upload_test_artifacts.sh
Labels: Low priority

#847 README: Add nmstate-0.2-git Copr repository
  README.md
Labels: Wait_Review

#860 nm.checkpoint: fix incorrect interval when adding a timer
  libnmstate/nm/checkpoint.py
Labels: Wait_Review

#855 examples: add sr-iov example yaml
  examples/eth0_with_sriov.yml
  tests/integration/examples_test.py
Labels: Waiting_Rebase

#862 validator: Drop unnused parameter at validate_interfaces_state()
  libnmstate/netapplier.py
  libnmstate/validator.py
  tests/lib/validator_test.py
Labels: Wait_Review

#863 nm sriov: Properly return when device not exists
  examples/eth1_with_sriov.yml
  libnmstate/nm/sriov.py
  tests/integration/examples_test.py
Labels: Wait_Review

#852 ActiveConnection: Handle uninitialized device
  libnmstate/nm/active_connection.py
Labels: backport candidate

#859 test: Add test case for know failure on switching from DHCP to static
  tests/integration/dynamic_ip_test.py
Labels: Waiting_Rebase

#876 travis: Use NM-1.22-git Copr repository for integration tests
  .travis.yml
Labels: Wait_Review
