Repository nmstate/nmstate, pull requests merged in 2021-09, with the labels that each got.

#1688 k8s, ci: bump centos stream at nodes
  k8s/kubevirtci.sh
  k8s/up.sh
Labels: Wait_on_submitter

#1698 nm.connection: do not rename existing connections
  libnmstate/nm/connection.py
  tests/integration/nm/profile_test.py
Labels: Wait_Review, Backport_Candicate

#1700 [nmstate-1.1] nm.connection: do not rename existing connections
  libnmstate/nm/connection.py
  tests/integration/nm/profile_test.py
Labels: Wait_Review

#1699 nm.connection: add prefixes to OVS bridges and interfaces connections
  libnmstate/nm/connection.py
  tests/integration/nm/profile_test.py
Labels: Wait_Review, Backport_Candicate

#1702 dns: Improve error message on DNS interface not found
  libnmstate/dns.py
  tests/lib/dns_test.py
Labels: Wait_Review
