Repository nmstate/nmstate, pull requests merged in 2021-06, with the labels that each got.

#1613 [nmstate-1.0] nm bond: Fixing `tlb_dynamic_lb` option
  libnmstate/nm/bond.py
  tests/integration/bond_test.py
Labels: Wait_Review

#1612 nm bond: Fixing `tlb_dynamic_lb` option
  libnmstate/nm/bond.py
  tests/integration/bond_test.py
Labels: Wait_Review

#1615 [nmstate-1.0] nm bond: Fix preserving `all_slaves_active` option
  libnmstate/nm/bond.py
  tests/integration/bond_test.py
Labels: Wait_Review

#1614 nm bond: Fix preserving `all_slaves_active` option
  libnmstate/nm/bond.py
  tests/integration/bond_test.py
Labels: Wait_Review

#1616 bond: Fix bond fail_over_mac=active
  libnmstate/ifaces/bond.py
  tests/integration/bond_test.py
  tests/lib/ifaces/bond_iface_test.py
Labels: Waiting_Rebase

#1617 [nmstate-1.0] bond: Fix bond fail_over_mac=active
  libnmstate/ifaces/bond.py
  tests/integration/bond_test.py
  tests/lib/ifaces/bond_iface_test.py
Labels: Wait_Review

#1595 nispor: Use ethtool link mode for speed/auto-negotiation/duplex.
  libnmstate/ethtool.py
  libnmstate/ifaces/ethernet.py
  libnmstate/nispor/ethernet.py
  libnmstate/nm/connection.py
  libnmstate/nm/plugin.py
  libnmstate/nm/wired.py
  requirements.txt
  tests/lib/ifaces/ethernet_iface_test.py
  tests/lib/nm/wired_test.py
Labels: Waiting_Rebase

#1624 bond: Don't validate current bond status
  libnmstate/ifaces/bond.py
Labels: Wait_Review

#1625 [nmstate-1.0] bond: Don't validate current bond status
  libnmstate/ifaces/bond.py
Labels: Wait_Review

#1621 nm ethtool: Use only original desire to update settings
  libnmstate/ifaces/__init__.py
  libnmstate/nm/connection.py
  libnmstate/nm/ethtool.py
  tests/lib/nm/ethtool_test.py
Labels: Waiting_Rebase

#1623 [nmstate-0.3] bond: Fix bond fail_over_mac=active
  libnmstate/ifaces/bond.py
  tests/integration/bond_test.py
  tests/lib/ifaces/bond_iface_test.py
Labels: Wait_on_submitter

#1618 bond: Handle multicast mac address of ad_actor_system
  libnmstate/ifaces/bond.py
  tests/integration/bond_test.py
Labels: Waiting_Rebase

#1626 nm: Sort activation in alphabet order explicitly
  libnmstate/nm/profiles.py
Labels: Wait_Review

#1627 nm: Sleep before retry activation
  libnmstate/nm/active_connection.py
Labels: Wait_Review

#1622 test: Only remove route/dns/route_rule before test
  tests/integration/conftest.py
  tests/integration/dynamic_ip_test.py
  tests/integration/nm/dns_test.py
  tests/integration/route_test.py
Labels: Wait_Review

#1628 bridge/bond: User permanent MAC address for `Interface.COPY_MAC_FROM`
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/ifaces.py
  libnmstate/nispor/base_iface.py
  tests/integration/conftest.py
  tests/integration/linux_bridge_test.py
  tests/lib/ifaces_test.py
  tests/lib/testlib/constants.py
Labels: Wait_Review

#1601 ethtool: Add support of coalesce
  libnmstate/ifaces/ethtool.py
  libnmstate/nispor/base_iface.py
  libnmstate/nm/ethtool.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  tests/integration/ethtool_test.py
  tests/lib/nm/ethtool_test.py
  tests/lib/schema_validation_test.py
Labels: Wait_Review

#1630 VERSION: Bump to 2.0.0
  libnmstate/VERSION
Labels: Wait_Review

#1632 test: Add test case for VLAN parent as inactive profile
  tests/integration/nm/linux_bridge_test.py
Labels: Wait_Review

#1634 [nmstate-1.1] test: Add test case for VLAN parent as inactive profile
  tests/integration/nm/linux_bridge_test.py
Labels: Wait_Review

#1633 [nmstate-1.0] test: Add test case for VLAN parent as inactive profile
  tests/integration/nm/linux_bridge_test.py
Labels: Wait_Review

#1631 [nmstate-0.3] nm connection: Only use active connection for VLAN parent UUID
  libnmstate/nm/applier.py
  tests/integration/nm/linux_bridge_test.py
Labels: Wait_Review

#1629 ethtool: support backwards compatibility with NM 1.26
  libnmstate/nm/ethtool.py
  tests/integration/ethtool_test.py
Labels: Waiting_Rebase

#1637 libnmstate: do not report perm_mac_address when showing
  libnmstate/netapplier.py
  libnmstate/netinfo.py
  libnmstate/nmstate.py
Labels: Wait_Review

#1639 [nmstate-1.1] libnmstate: do not report perm_mac_address when showing
  libnmstate/netapplier.py
  libnmstate/netinfo.py
  libnmstate/nmstate.py
Labels: Wait_Review

#1642 format: Upgrade to black-21.6b0
  tests/integration/nm/checkpoint.py
  tests/integration/nmstatectl_test.py
  tests/integration/testlib/assertlib.py
  tests/integration/testlib/ifacelib.py
  tox.ini
Labels: Wait_Review

#1638 [nmstate-1.1] ethtool: support backwards compatibility with NM 1.26
  libnmstate/nm/ethtool.py
  tests/integration/ethtool_test.py
Labels: Waiting_Rebase

#1640 nm wired: Preserve existing wired setting
  libnmstate/nm/connection.py
  tests/integration/nm/profile_test.py
Labels: Wait_Review

#1641 [nmstate-1.1] nm wired: Preserve existing wired setting
  libnmstate/nm/connection.py
  tests/integration/nm/profile_test.py
Labels: Waiting_Rebase

#1636 nmstate: fix SR-IOV issues with BCM driver
  libnmstate/ifaces/ethernet.py
  libnmstate/nm/profiles.py
Labels: Wait_Review

#1644 [nmstate-1.0] nm test: Add test for preserving wired setting
  tests/integration/nm/profile_test.py
Labels: Wait_Review

#1643 [nmstate-1.1] SR-IOV: Fix BCM57416 failure when creating VFs
  libnmstate/ifaces/ethernet.py
  libnmstate/nm/profiles.py
Labels: Wait_Review

#1647 nm: Fix the format string
  libnmstate/nm/plugin.py
Labels: Wait_Review

#1646 iface: The original desire should be empty for non-desired interface
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/bond.py
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/linux_bridge.py
  libnmstate/ifaces/ovs.py
  libnmstate/nm/bond.py
  libnmstate/nm/connection.py
  libnmstate/nm/profile.py
  libnmstate/nm/wired.py
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  tests/lib/ifaces/base_iface_test.py
  tests/lib/ifaces/ethernet_iface_test.py
  tests/lib/ifaces/linux_bridge_iface_test.py
  tests/lib/ifaces_test.py
  tests/lib/nm/bond_test.py
  tests/lib/nm/wired_test.py
Labels: Wait_Review

#1648 [nmstate-1.1] iface: The original desire should be empty for non-desired interface
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/bond.py
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/linux_bridge.py
  libnmstate/ifaces/ovs.py
  libnmstate/nm/bond.py
  libnmstate/nm/connection.py
  libnmstate/nm/profile.py
  libnmstate/nm/wired.py
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  tests/lib/ifaces/base_iface_test.py
  tests/lib/ifaces/ethernet_iface_test.py
  tests/lib/ifaces/linux_bridge_iface_test.py
  tests/lib/ifaces_test.py
  tests/lib/nm/bond_test.py
  tests/lib/nm/wired_test.py
Labels: Wait_Review

#1650 vrf: Ignore MAC and accept_all_mac_addresses=false
  libnmstate/ifaces/vrf.py
  tests/integration/vrf_test.py
  tests/lib/ifaces/vrf_iface_test.py
Labels: Backport_Candicate, Waiting_Rebase

#1651 bond: Use perm_hwaddr of bond port as fallback for copy_mac_from
  libnmstate/nispor/base_iface.py
  tests/integration/bond_test.py
Labels: Backport_Candicate, Waiting_Rebase

#1655 bridge, bond: drop slave support from schema
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  tests/lib/schema_deprecation_test.py
Labels: Wait_Review

#1654 nm: iterate the main context when refresh required
  libnmstate/nm/context.py
  libnmstate/nm/plugin.py
Labels: Wait_Review

#1656 varlink: Drop varlink support
  CONTRIBUTING.md
  doc/nmstatectl.8.in
  nmstatectl/README.varlink.md
  nmstatectl/nmstate-varlink.service
  nmstatectl/nmstate_varlink.py
  nmstatectl/nmstatectl.py
  packaging/Dockerfile.centos-stream-nmstate-dev
  packaging/Dockerfile.centos8-nmstate-dev
  packaging/Dockerfile.fedora-nmstate-dev
  packaging/nmstate.spec
  requirements.txt
  setup.py
  tests/integration/varlink_service_test.py
Labels: Waiting_Rebase

#1653 ifaces: Remove PERMANENT_MAC_ADDRESS_METADATA before verification
  libnmstate/ifaces/base_iface.py
  tests/lib/ifaces/base_iface_test.py
Labels: Backport_Candicate, Waiting_Rebase

#1657 802.1x: Hide the password from output by default
  doc/nmstatectl.8.in
  libnmstate/ifaces/base_iface.py
  libnmstate/netapplier.py
  libnmstate/netinfo.py
  libnmstate/nmstate.py
  libnmstate/state.py
  nmstatectl/nmstatectl.py
  tests/ctl/nmstatectl_test.py
  tests/integration/nm/ieee802_1x_test.py
  tests/integration/testlib/assertlib.py
  tests/integration/testlib/statelib.py
  tests/lib/ifaces/base_iface_test.py
Labels: Backport_Candicate, Wait_Review

#1652 SR-IOV: Fix issue when VF pre-exist before PF changes.
  libnmstate/ifaces/ethernet.py
  libnmstate/ifaces/ifaces.py
  libnmstate/nm/profiles.py
  tests/lib/ifaces_test.py
Labels: Backport_Candicate, Waiting_Rebase
