Repository nmstate/nmstate, pull requests merged in 2021-01, with the labels that each got.

#1453 sriov: Use verification retry to wait VF been created
  libnmstate/ifaces/ethernet.py
  libnmstate/ifaces/ifaces.py
  libnmstate/nispor/ethernet.py
  libnmstate/nm/profile.py
  tests/integration/sriov_test.py
  tests/lib/ifaces_test.py
Labels: Wait_Review

#1444 [nmstate-0.3] varlink: Fix the logger
  nmstatectl/nmstate_varlink.py
Labels: Wait_on_submitter

#1452 .github: enable github actions using ubuntu
  .github/workflows/main.yml
  tox.ini
Labels: Wait_on_submitter

#1456 CI: Moved to github action
  .github/workflows/main.yml
  .github/workflows/run_test.sh
  automation/tests-container-utils.sh
  automation/upload_test_artifacts.key
  automation/upload_test_artifacts.sh
Labels: Wait_Review

#1455 [nmstate-0.3] sriov: Use verification retry to wait VF been created
  libnmstate/ifaces/ethernet.py
  libnmstate/ifaces/ifaces.py
  libnmstate/nm/sriov.py
  libnmstate/nm/wired.py
  tests/integration/sriov_test.py
  tests/lib/nm/wired_test.py
Labels: Wait_Review

#1459 travis: remove .travis.yml file
  .travis.yml
  README.md
Labels: Wait_Review

#1458 CI: Enable test on OVS 2.11
  .github/workflows/main.yml
  .github/workflows/run_test.sh
Labels: Wait_Review

#1462 nm.connection: use iface type and object on setting creation
  libnmstate/ifaces/macvlan.py
  libnmstate/nm/connection.py
  libnmstate/nm/macvlan.py
  libnmstate/nm/vrf.py
  tests/lib/ifaces/mac_vlan_test.py
Labels: Wait_Review

#1464 veth: deactivate first only if peer is changed
  libnmstate/ifaces/veth.py
  libnmstate/nm/profile.py
  tests/integration/veth_test.py
Labels: Wait_Review

#1465 veth: retry import device when activating new veth peer
  libnmstate/nm/profile.py
  tests/integration/veth_test.py
Labels: Wait_Review

#1468 nm: Better handling for timeout
  libnmstate/nm/active_connection.py
  libnmstate/nm/context.py
  libnmstate/nm/profile.py
  tests/integration/timeout_test.py
Labels: Work_Ongoing

#1423 ovsdb: Support managing `Open_vSwitch` table
  libnmstate/net_state.py
  libnmstate/nmstate.py
  libnmstate/plugin.py
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  tests/integration/ovs_test.py
Labels: Consumer_QE_Approved, New Feature, Wait_QE

#1470 [nmstate-0.3] nm: Better handling for timeout
  libnmstate/nm/connection.py
  libnmstate/nm/context.py
  tests/integration/timeout_test.py
  tests/lib/nm/connection_test.py
Labels: Wait_Review

#1471 nm: Removing unneeded data refreshment
  libnmstate/nm/profile.py
Labels: Wait_Review

#1473 nm: Use fallback checker on profile deactivation and delete
  libnmstate/nm/active_connection.py
  libnmstate/nm/profile.py
Labels: Wait_Review

#1476 nm.context: remove refresh_content() calls
  libnmstate/nm/context.py
  libnmstate/nm/plugin.py
  tests/integration/nm/checkpoint.py
Labels: Wait_Review

#1481 [nmstate-0.3] nm: Use fallback checker on profile deactivation and delete
  libnmstate/nm/active_connection.py
  libnmstate/nm/connection.py
Labels: Wait_Review

#1482 ifaces: mark iface as changed when only when modified
  libnmstate/ifaces/ifaces.py
Labels: Wait_Review

#1484 ifaces: Don't validate undesired interface for overbook
  libnmstate/ifaces/ifaces.py
  tests/lib/ifaces_test.py
Labels: Wait_Review

#1486 nm: Only update NM.Device when valid
  libnmstate/nm/active_connection.py
Labels: Wait_Review

#1485 [nmstate-0.3] ifaces: Don't validate undesired interface for overbook
  libnmstate/ifaces/ifaces.py
  tests/lib/ifaces_test.py
Labels: Waiting_Rebase

#1488 veth: OVS controller must be activated before the veth
  libnmstate/nm/profile.py
Labels: Wait_Review

#1478 CHANGELOG: New release 1.0.1
  CHANGELOG
Labels: Consumer_QE_Approved, QE_Approved

#1490 VERSION: Bump to 1.0.2
  libnmstate/VERSION
Labels: Wait_Review

#1492 nm.active_connetion: retry on profile activation if libnm error happened
  libnmstate/nm/active_connection.py
  libnmstate/nm/device.py
Labels: Wait_Review

#1487 [nmstate-0.3] nm vlan/vxlan: Use uuid for VLAN/VxLAN parent
  libnmstate/nm/applier.py
  libnmstate/nm/connection.py
  tests/integration/nm/ovs_test.py
Labels: Wait_Review

#1493 nmstatectl: deprecate "set" in favor of "apply"
  doc/nmstatectl.8.in
  nmstatectl/nmstatectl.py
  tests/integration/nmstatectl_test.py
Labels: Wait_Review

#1498 github: remove Edy github PR default reviewer
  .github/CODEOWNERS
Labels: Waiting_Rebase

#1500 .github: add vdsm tests to CI
  .github/workflows/main.yml
  .github/workflows/run_test.sh
Labels: Wait_Review
