Repository nmstate/nmstate, pull requests merged in 2021-11, with the labels that each got.

#1723 rust nm: Fix reapply function
  rust/src/lib/iface.rs
  rust/src/lib/nm/apply.rs
  rust/src/lib/nm/connection.rs
  rust/src/libnm_dbus/nm_api.rs
Labels: Wait_Review

#1721 rust, ip: Fix deserialization/serialization of ipv4/ipv6
  rust/src/lib/ip.rs
Labels: Wait_Review

#1722 rust ovs: Support OpenvSwitch
  automation/run-tests.sh
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/base.rs
  rust/src/lib/ifaces/dummy.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/ifaces/inter_ifaces_controller.rs
  rust/src/lib/ifaces/mod.rs
  rust/src/lib/ifaces/ovs.rs
  rust/src/lib/ip.rs
  rust/src/lib/lib.rs
  rust/src/lib/net_state.rs
  rust/src/lib/nispor/apply.rs
  rust/src/lib/nispor/base_iface.rs
  rust/src/lib/nispor/show.rs
  rust/src/lib/nm/active_connection.rs
  rust/src/lib/nm/apply.rs
  rust/src/lib/nm/connection.rs
  rust/src/lib/nm/mod.rs
  rust/src/lib/nm/ovs.rs
  rust/src/lib/nm/profile.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/nm/unit_tests/mod.rs
  rust/src/lib/nm/unit_tests/profiles.rs
  rust/src/lib/unit_tests/ifaces.rs
  rust/src/lib/unit_tests/ifaces_ctrller.rs
  rust/src/lib/unit_tests/mod.rs
  rust/src/lib/unit_tests/testlib.rs
  rust/src/libnm_dbus/connection/conn.rs
  rust/src/libnm_dbus/connection/mod.rs
  rust/src/libnm_dbus/connection/ovs.rs
  rust/src/libnm_dbus/connection/wired.rs
  rust/src/libnm_dbus/dbus_value.rs
  rust/src/libnm_dbus/lib.rs
  rust/src/libnm_dbus/nm_api.rs
  tests/integration/ovs_test.py
  tests/integration/testlib/statelib.py
Labels: Wait_Review

#1727 rust libnm_dbus: Preserve unsupported options in NmConnection
  rust/src/lib/nm/bridge.rs
  rust/src/lib/nm/connection.rs
  rust/src/lib/nm/ip.rs
  rust/src/libnm_dbus/connection/bridge.rs
  rust/src/libnm_dbus/connection/conn.rs
  rust/src/libnm_dbus/connection/ip.rs
  rust/src/libnm_dbus/connection/ovs.rs
  rust/src/libnm_dbus/connection/wired.rs
  rust/src/libnm_dbus/dbus_value.rs
  rust/src/libnm_dbus/keyfile.rs
  rust/src/libnm_dbus/lib.rs
Labels: Wait_Review

#1731 packit: Enable copr build for CentOS Stream 9
  .packit.yml
Labels: Wait_Review

#1734 [nmstate-1.1] nm.connection: add postfixes to OVS bridges and interfaces connections
  libnmstate/nm/connection.py
  tests/integration/nm/profile_test.py
Labels: Wait_Review

#1729 rust nm: Preserve existing configurations
  automation/run-tests.sh
  rust/src/lib/nm/bridge.rs
  rust/src/lib/nm/connection.rs
  rust/src/lib/nm/ip.rs
  rust/src/lib/nm/mod.rs
  rust/src/lib/nm/ovs.rs
  rust/src/lib/nm/unit_tests/profiles.rs
  rust/src/lib/nm/wired.rs
Labels: Wait_Review

#1724 ovs: remove ovs-port- prefix for OVS bridge LAG ports
  libnmstate/nm/connection.py
  libnmstate/nm/ovs.py
  tests/integration/nm/ovs_test.py
Labels: Backport_Candicate, ok-to-test

#1732 rust: support MTU property
  automation/run-tests.sh
  rust/src/lib/ifaces/base.rs
  rust/src/lib/nm/wired.rs
  rust/src/libnm_dbus/connection/wired.rs
Labels: Wait_Review

#1741 rust: Add support for dummy interfaces
  automation/run-tests.sh
  rust/src/lib/nispor/base_iface.rs
  rust/src/lib/nm/connection.rs
Labels: Wait_Review, needs-ok-to-test

#1736 rust: linux bridge
  automation/run-tests.sh
  rust/src/lib/Cargo.toml
  rust/src/lib/error.rs
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/base.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/ifaces/inter_ifaces_controller.rs
  rust/src/lib/ifaces/linux_bridge.rs
  rust/src/lib/ifaces/mod.rs
  rust/src/lib/ip.rs
  rust/src/lib/lib.rs
  rust/src/lib/nispor/ethernet.rs
  rust/src/lib/nispor/linux_bridge.rs
  rust/src/lib/nispor/linux_bridge_port_vlan.rs
  rust/src/lib/nispor/mod.rs
  rust/src/lib/nispor/show.rs
  rust/src/lib/nispor/veth.rs
  rust/src/lib/nispor/vlan.rs
  rust/src/lib/nm/apply.rs
  rust/src/lib/nm/bridge.rs
  rust/src/lib/nm/connection.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/state.rs
  rust/src/libnm_dbus/connection/bridge.rs
  rust/src/libnm_dbus/connection/conn.rs
  rust/src/libnm_dbus/connection/mod.rs
  rust/src/libnm_dbus/convert.rs
  rust/src/libnm_dbus/lib.rs
  rust/src/libnm_dbus/nm_api.rs
  rust/src/python/libnmstate/clib_wrapper.py
  tests/integration/linux_bridge_test.py
Labels: Wait_Review
