Repository nmstate/nmstate, pull requests merged in 2021-05, with the labels that each got.

#1578 nm.wired: add support to accept-all-mac-addresses
  libnmstate/nispor/base_iface.py
  libnmstate/nm/wired.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  tests/integration/interface_common_test.py
  tests/integration/nmstatectl_test.py
  tests/integration/plugin_test.py
  tests/lib/schema_validation_test.py
Labels: QE_Approved

#1580 net_state: mark ifaces as ignored earlier
  libnmstate/dns.py
  libnmstate/net_state.py
  libnmstate/netapplier.py
  tests/integration/nm/dns_test.py
Labels: Wait_Review

#1582 nm.profile: activate modified ovs-port first
  libnmstate/nm/profile.py
  tests/integration/nm/ovs_test.py
Labels: Wait_Review

#1586 tests, integ: create a vlan with different name and id
  tests/integration/vlan_test.py
Labels: Wait_Review

#1591 CI: Fix centos stream container
  packaging/Dockerfile.centos-stream-nmstate-dev
Labels: Wait_Review

#1593 pytest: Fix warning of unregistered marker
  tests/integration/conftest.py
Labels: Wait_Review

#1592 ethtool: Introduce pause support
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/ethtool.py
  libnmstate/nispor/base_iface.py
  libnmstate/nm/connection.py
  libnmstate/nm/ethtool.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  tests/integration/ethtool_test.py
  tests/lib/ifaces/ethtool_test.py
  tests/lib/nm/ethtool_test.py
  tests/lib/schema_validation_test.py
Labels: Wait_QE

#1583 ovs: Fix `is_ovs_running()` in container environment.
  libnmstate/ifaces/ovs.py
  libnmstate/nm/active_connection.py
  libnmstate/nm/plugin.py
  libnmstate/validator.py
  tests/integration/examples_test.py
  tests/integration/ovs_test.py
Labels: Waiting_Rebase

#1590 tests, integ: extend accept-all-mac-addresses testing
  tests/integration/bond_test.py
  tests/integration/linux_bridge_test.py
  tests/integration/veth_test.py
  tests/integration/vlan_test.py
  tests/integration/vxlan_test.py
Labels: Waiting_Rebase

#1563 test, veth: remove peer connection on veth removal
  tests/integration/nm/veth_test.py
  tests/integration/testlib/veth.py
Labels: Wait_Review

#1597 README: Modify IRC server reference
  README.md
Labels: Wait_Review

#1599 CI: Remove NM main test on CentOS 8
  .github/workflows/main.yml
Labels: Wait_Review

#1603 CI: install libndp as new dependency of NetworkManager
  automation/run-tests.sh
  packaging/Dockerfile.centos-stream-nmstate-dev
Labels: Wait_Review

#1604 CI: make sure centos-stream install NetworkManager-ovs
  automation/run-tests.sh
Labels: Wait_Review

#1602 nm ipv4: Deactivate profile when route removed.
  libnmstate/nm/profile.py
  libnmstate/route.py
  tests/integration/route_test.py
Labels: Waiting_Rebase

#1607 [nmstate-1.0] ovs: Fix `is_ovs_running()` in container environment.
  libnmstate/ifaces/ovs.py
  libnmstate/nm/active_connection.py
  libnmstate/nm/plugin.py
  libnmstate/validator.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#1608 [nmstate-1.0] nm ipv4: Deactivate profile when route removed.
  libnmstate/nm/profile.py
  libnmstate/route.py
  tests/integration/route_test.py
Labels: Wait_Review
