Repository nmstate/nmstate, pull requests merged in 2021-07, with the labels that each got.

#1660 nm ovs: Fix OVS bridge and interface using the same name
  libnmstate/nm/device.py
  libnmstate/nm/plugin.py
  libnmstate/nm/profiles.py
  tests/integration/ovs_test.py
Labels: Backport_Candicate, Wait_Review

#1662 [nmstate-1.1] nm ovs: Fix OVS bridge and interface using the same name
  libnmstate/nm/device.py
  libnmstate/nm/plugin.py
  libnmstate/nm/profiles.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#1664 CI: install procps-ng for centos-stream
  packaging/Dockerfile.centos-stream-nmstate-dev
Labels: Wait_Review

#1665 [nmstate-1.1] CI: install procps-ng for centos-stream
  packaging/Dockerfile.centos-stream-nmstate-dev
Labels: Wait_Review

#1666 [nmstate-1.0] CI: install procps-ng for centos-stream
  packaging/Dockerfile.centos-stream-nmstate-dev
Labels: Wait_Review

#1670 ovs: Regenerate iface metadata after RouteRule metadata generation
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/linux_bridge.py
  libnmstate/net_state.py
  tests/integration/ovs_test.py
Labels: Wait_on_submitter

#1667 [nmstate-1.0] SR-IOV: Fix BCM57416 failure when creating VFs
  libnmstate/ifaces/ethernet.py
  libnmstate/nm/profiles.py
Labels: Wait_Review

#1668 [nmstate-1.1] ovs: Regenerate iface metadata after RouteRule metadata generation
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/linux_bridge.py
  libnmstate/net_state.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#1671 [nmstate-1.0] ovs: Regenerate iface metadata after RouteRule metadata generation
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/ifaces.py
  libnmstate/ifaces/linux_bridge.py
  libnmstate/net_state.py
  tests/integration/ovs_test.py
Labels: Waiting_Rebase

#1663 validator: drop jsonschema dependency
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/bond.py
  libnmstate/ifaces/ethernet.py
  libnmstate/ifaces/ethtool.py
  libnmstate/ifaces/infiniband.py
  libnmstate/ifaces/linux_bridge.py
  libnmstate/ifaces/macvlan.py
  libnmstate/ifaces/ovs.py
  libnmstate/ifaces/veth.py
  libnmstate/ifaces/vlan.py
  libnmstate/ifaces/vrf.py
  libnmstate/ifaces/vxlan.py
  libnmstate/netapplier.py
  libnmstate/nmstate.py
  libnmstate/route.py
  libnmstate/route_rule.py
  libnmstate/schema.py
  libnmstate/schemas/operational-state.yaml
  libnmstate/validator.py
  packaging/Dockerfile.centos-stream-nmstate-dev
  packaging/Dockerfile.centos8-nmstate-dev
  packaging/Dockerfile.fedora-nmstate-dev
  requirements.txt
  setup.py
  tests/integration/ethernet_mtu_test.py
  tests/lib/ifaces/base_iface_test.py
  tests/lib/ifaces/ethernet_iface_test.py
  tests/lib/ifaces/ethtool_test.py
  tests/lib/ifaces/infiniband_test.py
  tests/lib/ifaces/linux_bridge_iface_test.py
  tests/lib/ifaces/mac_vlan_test.py
  tests/lib/ifaces/ovs_iface_test.py
  tests/lib/ifaces/veth_iface_test.py
  tests/lib/ifaces/vlan_iface_test.py
  tests/lib/ifaces/vrf_iface_test.py
  tests/lib/ifaces/vxlan_iface_test.py
  tests/lib/ifaces_test.py
  tests/lib/schema_validation_test.py
  tests/lib/validator_test.py
  tox.ini
Labels: Wait_Review

#1673 ifaces: fix validation of base_iface properties
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/bond.py
  libnmstate/ifaces/ethernet.py
  libnmstate/ifaces/ethtool.py
  libnmstate/ifaces/infiniband.py
  libnmstate/ifaces/linux_bridge.py
  libnmstate/ifaces/macvlan.py
  libnmstate/ifaces/ovs.py
  libnmstate/ifaces/vlan.py
  libnmstate/ifaces/vrf.py
  libnmstate/ifaces/vxlan.py
Labels: Wait_Review

#1674 [nmstate-1.1] nmstate-autoconf: introduce nmstate-autoconf support
  MANIFEST.in
  doc/nmstate-autoconf.8.in
  nmstatectl/nmstate_autoconf.py
  packaging/nmstate.spec
  setup.py
  tests/integration/nmstate_autoconf_test.py
  tests/integration/test_captures/lldp_mgmtnet.pcap
  tests/integration/test_captures/lldp_prodnet.pcap
Labels: Wait_Review

#1658 nmstate-autoconf: introduce nmstate-autoconf support
  MANIFEST.in
  doc/nmstate-autoconf.8.in
  nmstatectl/nmstate_autoconf.py
  packaging/nmstate.spec
  setup.py
  tests/integration/nmstate_autoconf_test.py
  tests/integration/test_captures/lldp_mgmtnet.pcap
  tests/integration/test_captures/lldp_prodnet.pcap
Labels: Backport_Candicate, Wait_Review

#1676 [nmstate-1.1] VERSION: Bump to 1.1.1
  libnmstate/VERSION
Labels: Wait_Review

#1678 [nmstate-1.1] nmstatectl: fix long arguments support
  nmstatectl/nmstatectl.py
  tests/integration/nmstatectl_test.py
Labels: Wait_Review

#1679 nm ethtool: Preserve existing ethtool settings when undesired
  libnmstate/nm/connection.py
  libnmstate/nm/ethtool.py
  tests/integration/ethtool_test.py
  tests/lib/nm/ethtool_test.py
Labels: Backport_Candicate, Wait_Review

#1680 [nmstate-1.1] nm ethtool: Preserve existing ethtool settings when undesired
  libnmstate/nm/connection.py
  libnmstate/nm/ethtool.py
  tests/integration/ethtool_test.py
  tests/lib/nm/ethtool_test.py
Labels: Wait_Review

#1681 ovs: fix state=ignore for ovs port when removing them
  libnmstate/nm/profiles.py
  tests/integration/nm/ovs_test.py
Labels: Backport_Candicate, Wait_Review

#1682 [nmstate-1.1] ovs: fix state=ignore for ovs port when removing them
  libnmstate/nm/profiles.py
  tests/integration/nm/ovs_test.py
Labels: Wait_Review

#1683 nispor: fix show of empty next_hop_address and destination
  libnmstate/nispor/route.py
  tests/integration/route_test.py
Labels: Backport_Candicate

#1684 [nmstate-1.1] nispor: fix show of empty next_hop_address and destination
  libnmstate/nispor/route.py
  tests/integration/route_test.py
Labels: Wait_Review

#1686 [nmstate-1.0] CI: Install python3-jsonschema before test
  .github/workflows/run_test.sh
Labels: Wait_Review

#1685 [nmstate-1.0] nispor: fix show of empty next_hop_address and destination
  libnmstate/nispor/route.py
  tests/integration/route_test.py
Labels: Wait_Review
