Repository nmstate/nmstate, pull requests merged in 2022-10, with the labels that each got.

#2049 [nmstate-1.2] ovsdb: Raise exception if no ovsdb plugin when required
  libnmstate/plugin.py
  libnmstate/plugins/nmstate_plugin_ovsdb.py
  libnmstate/validator.py
  rust/src/python/libnmstate/__init__.py
  tests/integration/ovs_test.py
  tests/integration/testlib/env.py
Labels: Wait_Review

#2053 bond: Fix the bond `ad_select` option
  rust/src/lib/ifaces/bond.rs
Labels: Wait_Review

#2054 nispor: Use 1.2.8 version instead of git
  rust/src/lib/Cargo.toml
Labels: Wait_Review

#2044 nm: Fix dbus value type of coalesce-adaptive RX/TX
  rust/src/lib/nm/nm_dbus/connection/ethtool.rs
  tests/integration/nm/ethtool_test.py
Labels: Wait_Review

#2039 [nmstate-1.2] ip: allow extra IP address found in verification stage
  libnmstate/ifaces/base_iface.py
  libnmstate/schema.py
  tests/lib/ifaces/base_iface_test.py
  tests/lib/testlib/constants.py
Labels: Wait_Review

#2057 Improved README.md
  README.md
Labels: ok-to-test

#2058 cli yaml: Replace non-breaking space with normal space
  rust/src/cli/apply.rs
  rust/src/cli/gen_conf.rs
Labels: Wait_Review

#2047 ip: allow extra IP address found in verification stage
  rust/src/lib/ip.rs
  rust/src/lib/query_apply/base.rs
  rust/src/lib/query_apply/iface.rs
  rust/src/lib/query_apply/ip.rs
  rust/src/lib/unit_tests/base.rs
  rust/src/lib/unit_tests/ip.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/dynamic_ip_test.py
Labels: Wait_Review

#2059 deserialize: Deny unknown field in NetworkState
  rust/src/lib/net_state.rs
  rust/src/lib/unit_tests/mod.rs
  rust/src/lib/unit_tests/net_state.rs
Labels: Wait_Review

#2052 gen_conf: add support to route rules
  rust/src/lib/nm/nm_dbus/gen_conf/ip.rs
  rust/src/lib/nm/nm_dbus/gen_conf/route_rule.rs
  tests/integration/nm/gen_conf_test.py
Labels: Wait_Review

#2064 CI: Remove VDSM CI
  .github/workflows/main.yml
Labels: Wait_Review

#2062 gen_conf: Treating state:down as autoconnect false
  rust/src/lib/nm/gen_conf.rs
  tests/integration/nm/profile_test.py
Labels: Wait_Review

#2067 dependency: Update serde_yaml to 0.9
  rust/src/cli/Cargo.toml
  rust/src/lib/Cargo.toml
  rust/src/lib/ifaces/bridge_vlan.rs
Labels: Wait_Review

#2069 Bump to 2.2.1
  VERSION
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
  rust/src/python/libnmstate/__init__.py
  rust/src/python/setup.py
Labels: Wait_Review

#2073 key: Update Gris's gpg key
  nmstate.gpg
Labels: Wait_on_submitter

#2074 CI: On run release CI job on tag created
  .github/workflows/release.yml
Labels: Wait_Review
