Repository nmstate/nmstate, pull requests merged in 2022-06, with the labels that each got.

#1916 nm: Generate stable UUID for keyfile
  rust/src/lib/Cargo.toml
  rust/src/lib/nm/connection.rs
  rust/src/lib/nm/nm_dbus/Cargo.toml
  rust/src/lib/nm/ovs.rs
  rust/src/lib/nm/veth.rs
  tests/integration/examples_test.py
Labels: Wait_Review

#1904 DHCPv6: Add support of DUID
  rust/src/lib/ip.rs
  rust/src/lib/lib.rs
  rust/src/lib/nm/ip.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/dynamic_ip_test.py
Labels: Wait_Review

#1905 DHCPv4: Add support of client ID
  rust/src/lib/ip.rs
  rust/src/lib/lib.rs
  rust/src/lib/nm/ip.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/dynamic_ip_test.py
Labels: Wait_Review

#1917 cargo: Add description and etc to Cargo.toml
  rust/src/lib/Cargo.toml
Labels: Wait_Review

#1906 ipv6: Add support of `addr_gen_mode`
  rust/src/lib/ip.rs
  rust/src/lib/lib.rs
  rust/src/lib/nm/ip.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/dynamic_ip_test.py
Labels: Wait_Review

#1908 cli: Change default verbose level to `INFO`
  rust/src/cli/ncl.rs
Labels: Wait_Review

#1918 nm: Do not dump `NmConnection` to log
  rust/src/lib/nm/nm_dbus/connection/conn.rs
  rust/src/lib/nm/profile.rs
Labels: Wait_Review

#1911 hostname: Add support of static hostname modification
  examples/dynamic_hostname.yml
  examples/static_hostname.yml
  rust/src/cli/ncl.rs
  rust/src/lib/Cargo.toml
  rust/src/lib/hostname.rs
  rust/src/lib/lib.rs
  rust/src/lib/net_state.rs
  rust/src/lib/nispor/hostname.rs
  rust/src/lib/nispor/mod.rs
  rust/src/lib/nispor/show.rs
  rust/src/lib/nm/apply.rs
  rust/src/lib/nm/connection.rs
  rust/src/lib/nm/nm_dbus/dbus.rs
  rust/src/lib/nm/nm_dbus/dbus_proxy.rs
  rust/src/lib/nm/nm_dbus/nm_api.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/examples_test.py
  tests/integration/hostname_test.py
Labels: Wait_on_submitter

#1922 Fix clippy warnings
  rust/src/cli/autoconf.rs
  rust/src/lib/nispor/apply.rs
Labels: Wait_Review

#1926 Bump version to 2.1.2
  VERSION
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
  rust/src/python/libnmstate/__init__.py
  rust/src/python/setup.py
Labels: Wait_Review

#1927 nmstate.gpg: Modify Fernando Fernandez Mancera gpg key
  nmstate.gpg
Labels: Wait_Review

#1925 Cargo.toml: Fix license string
  rust/src/lib/Cargo.toml
Labels: Wait_Review

#1928 [nmstate-1.3] nm veth: Fix activation failure on IPv6 only new veth
  libnmstate/nm/profile.py
  tests/integration/veth_test.py
Labels: Wait_Review

#1929 test: Add test case for ipv6 only new veth
  tests/integration/veth_test.py
Labels: Wait_Review

#1931 CHANGELOG: New release 1.3.0
  CHANGELOG
Labels: Wait_Review

#1937 rust/clib: build both cdylib and staticlib
  rust/src/clib/Cargo.toml
Labels: needs-ok-to-test

#1939 RPM package nmstate static lib
  Makefile
  packaging/nmstate.spec.in
Labels: needs-ok-to-test

#1936 cli: Add service subcommand
  Makefile
  doc/nmstate.service.8.in
  doc/nmstatectl.8.in
  packaging/nmstate.service
  packaging/nmstate.spec.in
  rust/src/cli/ncl.rs
  rust/src/cli/service.rs
  tests/integration/nmstate_service_test.py
Labels: Wait_Review

#1943 bond: fix fail_over_mac follow mode
  rust/src/lib/ifaces/bond.rs
  tests/integration/bond_test.py
Labels: Wait_Review

#1938 linux bridge: Add support of vlan protocol
  rust/src/lib/ifaces/linux_bridge.rs
  rust/src/lib/ifaces/mod.rs
  rust/src/lib/ifaces/vlan.rs
  rust/src/lib/lib.rs
  rust/src/lib/nispor/linux_bridge.rs
  rust/src/lib/nm/bridge.rs
  rust/src/lib/nm/nm_dbus/connection/bridge.rs
  rust/src/lib/nm/nm_dbus/connection/vlan.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/linux_bridge_test.py
Labels: Wait_Review

#1940 nm ip: Clear gateway setting when converting to auto ip.
  rust/src/lib/nm/ip.rs
  tests/integration/nm/ip_test.py
Labels: Wait_Review

#1944 hostname: Fix applying different running and config hostname
  rust/src/lib/net_state.rs
  tests/integration/hostname_test.py
Labels: Wait_Review

#1948 Upgrade nispor dependency to 1.2.7
  rust/src/lib/Cargo.toml
Labels: Wait_Review

#1950 systemd: Include /etc/nmstate/README
  Makefile
  doc/nmstate.service.README
  packaging/nmstate.spec.in
Labels: Wait_Review

#1951 CHANGELOG: New release 2.1.2
  CHANGELOG
Labels: Wait_Review
