Repository nmstate/nmstate, pull requests merged in 2022-11, with the labels that each got.

#2076 doc: Add crate and NetworkState documentation
  rust/src/lib/gen_conf.rs
  rust/src/lib/lib.rs
  rust/src/lib/net_state.rs
  rust/src/lib/query_apply/net_state.rs
Labels: Wait_Review

#2077 doc: Add document for Interfaces and Interface
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/inter_ifaces.rs
Labels: Wait_Review

#2079 nm: Support `dns-data` in NetworkManager 1.41
  rust/src/lib/nm/nm_dbus/connection/dns.rs
  rust/src/lib/nm/nm_dbus/connection/ip.rs
Labels: Wait_Review

#2084 doc: Add document for BaseInterface and IP
  rust/src/lib/ifaces/base.rs
  rust/src/lib/ip.rs
Labels: Wait_Review

#2085 cargo: Minimum rust version 1.60
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
Labels: Wait_Review

#2083 nm: Fix deleting interface created by iproute
  rust/src/lib/nm/apply.rs
  tests/integration/linux_bridge_test.py
Labels: Wait_Review

#2093 CHANGELOG: Use conscious language
  CHANGELOG
Labels: Wait_Review

#2094 veth, tests: add veth peer renaming tests
  tests/integration/nm/veth_test.py
Labels: Wait_Review

#2080 [nmstate-1.3] ip: Preserve the IP address order when applying
  libnmstate/ifaces/base_iface.py
  tests/integration/static_ip_address_test.py
  tests/integration/testlib/env.py
  tests/integration/testlib/iproutelib.py
  tests/lib/ifaces/ip_state_test.py
Labels: Wait_on_submitter

#2090 nm infiniband: The infiniband parent cannot be UUID
  rust/src/lib/nm/settings/inter_connections.rs
Labels: Wait_Review

#2098 Make nmstate go module reflect v2
  rust/src/go/nmstate/go.mod
Labels: needs-ok-to-test

#2099 New release 2.2.1
  CHANGELOG
Labels: Wait_Review

#2100 Bump version to 2.2.2
  VERSION
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
  rust/src/python/libnmstate/__init__.py
  rust/src/python/setup.py
Labels: Wait_Review

#2108 Update README
  README.md
Labels: Wait_Review

#2105 dns: Support IPv6 link local address as DNS nameserver
  rust/src/lib/dns.rs
  rust/src/lib/net_state.rs
  rust/src/lib/nm/query/dns.rs
  rust/src/lib/nm/query/ip.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/query_apply/dns.rs
  rust/src/lib/unit_tests/dns.rs
  tests/integration/dynamic_ip_test.py
Labels: Wait_Review

#2102 iface: Add support of `controller` property
  rust/src/lib/ifaces/base.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/ifaces/inter_ifaces_controller.rs
  rust/src/lib/nm/settings/connection.rs
  rust/src/lib/nm/settings/inter_connections.rs
  rust/src/lib/query_apply/inter_ifaces.rs
  rust/src/lib/query_apply/net_state.rs
  rust/src/lib/unit_tests/ifaces_ctrller.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/linux_bridge_test.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#2110 README: Change the title
  README.md
Labels: Wait_Review

#2111 [nmstate-1.3] Update GPG keys in a single entry
  nmstate.gpg
Labels: Wait_Review

#2112 key: Add ffmancera updated GPG key back
  nmstate.gpg
Labels: Wait_Review

#2116 tests, ovs: add updelay and downdelay ovs-bond options test
  tests/integration/ovs_test.py
  tests/integration/testlib/ovslib.py
Labels: Wait_Review

#2125 CI: Drop actions-rs actions
  .github/workflows/main.yml
Labels: Wait_Review

#2126 [nmstate-1.3] CI: Drop actions-rs and upgrade actions/checkout to v3
  .github/workflows/main.yml
Labels: Wait_Review

#2122 Revert "packit: Remove the PR copr build for EPEL8 and EPEL9"
  .packit.yml
Labels: Wait_Review

#2127 Fix CI on NM 1.41 where loopback interface is supported
  rust/src/lib/nispor/base_iface.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/query_apply/iface.rs
Labels: Wait_Review

#2123 [nmstate-1.3] ethtool: fix ethtool feature highdma support
  libnmstate/ifaces/ethtool.py
  libnmstate/nispor/base_iface.py
  tests/integration/ethtool_test.py
Labels: Wait_Review

#2119 ifaces: Expose `iter()` and `iter_mut()`
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/unit_tests/ifaces.rs
Labels: Wait_Review

#2121 [nmstate-1.3] nm: Fix activation retry
  libnmstate/nm/active_connection.py
  tests/integration/veth_test.py
Labels: Wait_Other_PR, Wait_Review

#2124 controller: Fix detaching port from controller
  rust/src/lib/ifaces/inter_ifaces_controller.rs
  rust/src/lib/query_apply/base.rs
  tests/integration/linux_bridge_test.py
Labels: Wait_Other_PR, Wait_Review

#2129 k8s ci: Fix `test_ipv6_link_local_dns_srv`
  tests/integration/dynamic_ip_test.py
Labels: Wait_Review

#2132 Skip security leak check on automation/upload_test_artifacts.key
  .gitleaks.toml
Labels: Wait_Review

#2135 cargo: Less dependency
  rust/src/lib/Cargo.toml
Labels: Wait_Review
