Repository nmstate/nmstate, pull requests merged in 2023-03, with the labels that each got.

#2263 nm ovs dpdk: Fix `n-rxq-desc` and `n-txq-desc` properties
  rust/src/lib/nm/settings/ovs.rs
Labels: Wait_Review

#2264 cli: Support policy file in service mode
  rust/src/cli/apply.rs
  rust/src/cli/ncl.rs
  rust/src/cli/service.rs
  tests/integration/nmstate_service_test.py
Labels: Wait_Review

#2266 test: Add test case for OVS DPDK using gc mode
  tests/integration/nm/ovs_test.py
Labels: Wait_Review

#2257 vxlan: Add VXLAN properties for EVPN use
  rust/src/lib/ifaces/vxlan.rs
  rust/src/lib/nispor/vxlan.rs
  rust/src/lib/nm/nm_dbus/connection/vxlan.rs
  rust/src/lib/nm/settings/vxlan.rs
  rust/src/lib/query_apply/vxlan.rs
  rust/src/lib/unit_tests/vxlan.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/testlib/vxlan.py
  tests/integration/vxlan_test.py
Labels: Wait_on_submitter, needs-ok-to-test

#2265 nm: Retry when NetworkManager starting up
  rust/src/cli/service.rs
  rust/src/lib/query_apply/net_state.rs
Labels: Wait_Review

#2267 New release 2.2.8
  CHANGELOG
Labels: Wait_Review

#2268 Bump version to 2.2.9
  VERSION
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
  rust/src/python/libnmstate/__init__.py
  rust/src/python/setup.py
Labels: Wait_Review

#2278 [nmstate-1.3] Fix typo in supported features tx-gro -> rx-gro
  libnmstate/ifaces/ethtool.py
  libnmstate/nispor/base_iface.py
Labels: needs-ok-to-test

#2277 [nmstate-1.4] Fix typo in supported features tx-gro -> rx-gro
  libnmstate/ifaces/ethtool.py
  libnmstate/nispor/base_iface.py
Labels: needs-ok-to-test

#2271 [nmstate-1.4] ip: Preserver IP when converting unmanaged interface to managed
  libnmstate/nispor/base_iface.py
  tests/integration/nm/iproute_config_test.py
Labels: Wait_Review

#2270 [nmstate-1.2] ip: Preserver IP when converting unmanaged interface to managed
  libnmstate/nispor/base_iface.py
  tests/integration/nm/iproute_config_test.py
Labels: Wait_Review

#2273 nm dns: Do not use current interface which is unmanaged/external managed
  rust/src/lib/nm/dns.rs
  rust/src/lib/nm/gen_conf.rs
  rust/src/lib/nm/nm_dbus/active_connection.rs
  rust/src/lib/nm/nm_dbus/device.rs
  rust/src/lib/nm/nm_dbus/mod.rs
  rust/src/lib/nm/nm_dbus/nm_api.rs
  rust/src/lib/nm/nm_dbus/query_apply/device.rs
  rust/src/lib/nm/nm_dbus/query_apply/mod.rs
  rust/src/lib/nm/query_apply/apply.rs
  rust/src/lib/nm/query_apply/device.rs
  rust/src/lib/nm/query_apply/dns.rs
  rust/src/lib/nm/query_apply/mod.rs
  rust/src/lib/nm/settings/connection.rs
  rust/src/lib/nm/settings/mod.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/unit_tests/nm/dns.rs
  tests/integration/nm/dns_test.py
Labels: Wait_Review

#2269 cli: New subcommand `format`
  rust/src/cli/format.rs
  rust/src/cli/ncl.rs
Labels: Wait_Review

#2274 [nmstate-1.4] DNS: fix error when server has static DNS search with auto DNS server
  libnmstate/dns.py
  tests/integration/dynamic_ip_test.py
Labels: Wait_Review

#2275 [nmstate-1.2] DNS: fix error when server has static DNS search with auto DNS server
  libnmstate/dns.py
  tests/integration/dynamic_ip_test.py
Labels: Wait_Review

#2283 cli: Ignore failure when reading /etc/nmstate folder
  rust/src/cli/service.rs
  tests/integration/nmstate_service_test.py
Labels: Wait_Review

#2284 nmstate.service: remain after exit
  packaging/nmstate.service
  tests/integration/nmstate_service_test.py
Labels: ok-to-test

#2285 cli: Change install section of nmstate.service
  packaging/nmstate.service
Labels: Wait_Review

#2286 cli: Place nmstate.service before network-online.target
  packaging/nmstate.service
Labels: Wait_Review

#2282 test: Add test case for `nmstatectl format`
  tests/integration/nmstatectl_test.py
Labels: Wait_Review

#2287 nm: Refresh active connection after deletion
  rust/src/lib/nm/query_apply/apply.rs
  rust/src/lib/nm/query_apply/profile.rs
Labels: Wait_Review

#2289 CHANGELOG: Fix incorrect features for 2.2.9
  CHANGELOG
Labels: Wait_Review

#2290 Bump version to 2.2.10
  VERSION
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
  rust/src/python/libnmstate/__init__.py
  rust/src/python/setup.py
Labels: Wait_Review

#2295 test: Add test case for preserving IP order of external managed interface
  tests/integration/nm/iproute_config_test.py
  tests/integration/testlib/iproutelib.py
Labels: Wait_Review

#2296 [nmstate-1.4] rust: Sync rust code with 2.2.9
  rust/src/cli/apply.rs
  rust/src/cli/format.rs
  rust/src/cli/ncl.rs
  rust/src/cli/service.rs
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/inter_ifaces_controller.rs
  rust/src/lib/ifaces/vxlan.rs
  rust/src/lib/nispor/vxlan.rs
  rust/src/lib/nm/dns.rs
  rust/src/lib/nm/gen_conf.rs
  rust/src/lib/nm/nm_dbus/active_connection.rs
  rust/src/lib/nm/nm_dbus/connection/vxlan.rs
  rust/src/lib/nm/nm_dbus/device.rs
  rust/src/lib/nm/nm_dbus/mod.rs
  rust/src/lib/nm/nm_dbus/nm_api.rs
  rust/src/lib/nm/nm_dbus/query_apply/device.rs
  rust/src/lib/nm/nm_dbus/query_apply/mod.rs
  rust/src/lib/nm/query_apply/apply.rs
  rust/src/lib/nm/query_apply/device.rs
  rust/src/lib/nm/query_apply/dns.rs
  rust/src/lib/nm/query_apply/mod.rs
  rust/src/lib/nm/query_apply/profile.rs
  rust/src/lib/nm/settings/connection.rs
  rust/src/lib/nm/settings/mod.rs
  rust/src/lib/nm/settings/ovs.rs
  rust/src/lib/nm/settings/vlan.rs
  rust/src/lib/nm/settings/vxlan.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/query_apply/base.rs
  rust/src/lib/query_apply/inter_ifaces.rs
  rust/src/lib/query_apply/net_state.rs
  rust/src/lib/query_apply/vlan.rs
  rust/src/lib/query_apply/vxlan.rs
  rust/src/lib/route_rule.rs
  rust/src/lib/unit_tests/nm/dns.rs
  rust/src/lib/unit_tests/vlan.rs
  rust/src/lib/unit_tests/vxlan.rs
  rust/src/python/libnmstate/schema.py
Labels: Wait_Review

#2297 New release 1.4.3
  CHANGELOG
  libnmstate/VERSION
  rust/Makefile.inc
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
  rust/src/python/libnmstate/__init__.py
  rust/src/python/setup.py
Labels: Wait_Review

#2298 [nmstate-1.2] CI: Remove fedora container
  automation/run-tests.sh
Labels: Wait_Review
