Repository nmstate/nmstate, pull requests merged in 2023-10, with the labels that each got.

#2421 [nmstate-1.4] ip: Support treating string as int for `prefix-length`
  libnmstate/ifaces/base_iface.py
  libnmstate/schemas/operational-state.yaml
  tests/lib/ifaces/ip_state_test.py
Labels: Wait_Review

#2429 Validate prefix length for IP addresses
  rust/src/lib/ip.rs
  rust/src/lib/unit_tests/ip.rs
Labels: Waiting_Rebase, ok-to-test

#2418 bond: Add support for the ports-config
  examples/bond_port_absent.yml
  examples/bond_port_up.yml
  rust/src/cli/autoconf.rs
  rust/src/lib/deserializer.rs
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/bond.rs
  rust/src/lib/ifaces/mod.rs
  rust/src/lib/lib.rs
  rust/src/lib/nispor/bond.rs
  rust/src/lib/nispor/show.rs
  rust/src/lib/nm/nm_dbus/connection/bond.rs
  rust/src/lib/nm/nm_dbus/connection/conn.rs
  rust/src/lib/nm/nm_dbus/connection/mod.rs
  rust/src/lib/nm/nm_dbus/gen_conf/bond.rs
  rust/src/lib/nm/nm_dbus/gen_conf/conn.rs
  rust/src/lib/nm/nm_dbus/mod.rs
  rust/src/lib/nm/settings/bond.rs
  rust/src/lib/nm/settings/connection.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/bond_test.py
  tests/integration/examples_test.py
Labels: Wait_Review

#2426 ovn: Tidy up the ovs/ovn code
  rust/src/lib/ifaces/bond.rs
  rust/src/lib/lib.rs
  rust/src/lib/net_state.rs
  rust/src/lib/ovn.rs
  rust/src/lib/ovs.rs
  rust/src/lib/ovsdb/show.rs
  rust/src/lib/query_apply/net_state.rs
  rust/src/lib/query_apply/ovn.rs
  rust/src/lib/query_apply/ovs.rs
  rust/src/lib/unit_tests/ovn.rs
  rust/src/lib/unit_tests/ovsdb.rs
  tests/integration/ovs_test.py
Labels: Wait_Review

#2430 nit: improve English of few doc elements
  CHANGELOG
  rust/DEVEL.md
  rust/src/cli/ncl.rs
  rust/src/clib/nmstate.h.in
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/nm/query_apply/ip.rs
Labels: ok-to-test

#2417 macsec: rename parent property to base-iface
  examples/macsec0_up.yml
  rust/src/lib/ifaces/macsec.rs
  rust/src/lib/nispor/macsec.rs
  rust/src/lib/nm/settings/macsec.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/examples_test.py
  tests/integration/macsec_test.py
Labels: Wait_on_submitter

#2427 Support invoking dispatch script
  rust/src/lib/dispatch.rs
  rust/src/lib/ifaces/base.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/lib.rs
  rust/src/lib/nm/query_apply/apply.rs
  rust/src/lib/nm/query_apply/dispatch.rs
  rust/src/lib/nm/query_apply/mod.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/query_apply/base.rs
  rust/src/lib/query_apply/dispatch.rs
  rust/src/lib/query_apply/mod.rs
  tests/integration/nm/dispath_test.py
Labels: Wait_Review

#2433 Bump version to 2.2.18
  VERSION
  automation/upstream_release.sh
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
  rust/src/python/libnmstate/__init__.py
  rust/src/python/setup.py
Labels: Wait_Review

#2435 rpm: Fix `make rpm` failure in Fedora
  .github/workflows/build_rpm.sh
  .packit.yml
  Makefile
  automation/run-tests.sh
  packaging/Dockerfile.fed-nmstate-dev:latest
  packaging/Dockerfile.fed-nmstate-dev:rawhide
  packaging/nmstate.spec.in
Labels: Wait_Review

#2436 Revert "ci: Workaround for ip netns bug in container."
  tests/integration/conftest.py
Labels: Wait_Review
