Repository nmstate/nmstate, pull requests merged in 2023-01, with the labels that each got.

#2170 test: Retry till OVS interface shows up
  tests/integration/ovs_test.py
Labels: Wait_Review

#2167 ovsdb: Switch to ovsdb plugin for querying all OVS related info
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/ifaces/inter_ifaces_controller.rs
  rust/src/lib/ifaces/ovs.rs
  rust/src/lib/nm/profile.rs
  rust/src/lib/nm/query/mod.rs
  rust/src/lib/nm/query/ovs.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/ovs.rs
  rust/src/lib/ovsdb/db.rs
  rust/src/lib/ovsdb/show.rs
  rust/src/lib/query_apply/iface.rs
  rust/src/lib/query_apply/net_state.rs
  rust/src/lib/query_apply/ovs.rs
  tests/integration/examples_test.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#2174 test: Add test for assigning IP to detached port
  tests/integration/bond_test.py
Labels: Wait_Review

#2175 cargo: Support rust 1.58
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
  rust/src/lib/ifaces/inter_ifaces.rs
Labels: Wait_Review

#2176 ovs: Fix incorrect ovs bond mode
  rust/src/lib/ovsdb/show.rs
  tests/integration/ovs_test.py
Labels: Wait_Review

#2177 test: Ignore route metric in test
  tests/integration/route_test.py
Labels: Wait_Review

#2178 nm dns: Fix error when moving dns from port to controller
  rust/src/lib/iface.rs
  rust/src/lib/nm/dns.rs
  tests/integration/dns_test.py
  tests/integration/testlib/genconf.py
Labels: Wait_Review

#2179 ip: Empty IPv4 address should be considered as disabled
  rust/src/lib/ip.rs
  tests/integration/static_ip_address_test.py
Labels: Wait_Review

#2180 veth: No allowing creating veth without veth peer
  rust/src/lib/ifaces/ethernet.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/unit_tests/ethernet.rs
Labels: Wait_Review

#2169 test: Add test for vlan with both parent and controller
  rust/src/lib/unit_tests/vrf.rs
  tests/integration/vrf_test.py
Labels: Work_Ongoing

#2159 bridge vlan: Add more sanity check
  rust/src/lib/ifaces/bridge_vlan.rs
  rust/src/lib/ifaces/linux_bridge.rs
  rust/src/lib/ifaces/ovs.rs
  rust/src/lib/unit_tests/bridge.rs
  rust/src/lib/unit_tests/ovs.rs
Labels: Wait_Other_PR, Work_Ongoing

#2173 [nmstate-1.4] iface: Fix error when assigning IP to port of absent controller
  libnmstate/ifaces/base_iface.py
  libnmstate/ifaces/ifaces.py
  tests/integration/bond_test.py
Labels: Wait_Review

#2181 controller: Auto manage ignored port in desired controller
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/ifaces/inter_ifaces_controller.rs
  rust/src/lib/unit_tests/ifaces_ctrller.rs
  tests/integration/nm/linux_bridge_test.py
Labels: Wait_Review

#2182 nm route rule: Support searching default route table ID
  rust/src/lib/nm/route_rule.rs
  rust/src/lib/route_rule.rs
  rust/src/lib/unit_tests/nm/route_rule.rs
Labels: Wait_Review

#2184 ipv6: raise proper error when MTU < 1280 and IPV6 enabled
  rust/src/lib/ifaces/base.rs
  rust/src/lib/unit_tests/ip.rs
  tests/integration/ethernet_mtu_test.py
Labels: Wait_Review

#2185 New release 2.2.3
  CHANGELOG
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
  rust/src/python/libnmstate/__init__.py
  rust/src/python/setup.py
Labels: Wait_Review

#2187 New release 1.4.1
  CHANGELOG
Labels: Wait_Review

#2189 ovsdb: Fix verification error when ovs daemon off
  rust/src/lib/query_apply/ovs.rs
  rust/src/lib/unit_tests/ovsdb.rs
  tests/integration/ovs_test.py
  tests/integration/testlib/servicelib.py
Labels: Wait_Review

#2188 Bump version to 2.2.4
  VERSION
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
  rust/src/python/libnmstate/__init__.py
  rust/src/python/setup.py
Labels: Wait_Review

#2194 test bond: Retry when asserting MAC address
  tests/integration/bond_test.py
Labels: Wait_Review

#2191 route and route rule: Treat empty IP string as None
  rust/src/lib/route.rs
  rust/src/lib/route_rule.rs
  rust/src/lib/unit_tests/route.rs
  rust/src/lib/unit_tests/route_rule.rs
  tests/integration/route_test.py
Labels: Wait_Review

#2192 linux bridge: Handle group-fwd-mask conflict with group-forward-mask
  rust/src/lib/ifaces/linux_bridge.rs
  rust/src/lib/unit_tests/bridge.rs
Labels: Wait_Review

#2193 nm ovs: Do not delete OVS bond port still in use
  rust/src/lib/nm/query_apply/apply.rs
  rust/src/lib/nm/query_apply/ovs.rs
  tests/integration/ovs_test.py
Labels: Wait_Review

#2195 ovs: Support interface level `other_config` (api break)
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/base.rs
  rust/src/lib/ifaces/ovs.rs
  rust/src/lib/nm/nm_dbus/connection/conn.rs
  rust/src/lib/nm/nm_dbus/connection/mod.rs
  rust/src/lib/nm/nm_dbus/connection/ovs.rs
  rust/src/lib/nm/nm_dbus/gen_conf/conn.rs
  rust/src/lib/nm/nm_dbus/gen_conf/ovs.rs
  rust/src/lib/nm/nm_dbus/mod.rs
  rust/src/lib/nm/settings/connection.rs
  rust/src/lib/nm/settings/ovs.rs
  rust/src/lib/ovs.rs
  rust/src/lib/ovsdb/show.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/ovs_test.py
  tests/integration/testlib/assertlib.py
Labels: Wait_Review

#2196 mptcp: Fix mptcp error on older NetworkManager
  .github/workflows/main.yml
  .github/workflows/run_test.sh
  automation/run-tests.sh
  rust/src/lib/nm/profile.rs
  tests/integration/nm/ip_test.py
Labels: Wait_Review

#2183 ovs dpdk: Add support of `n_rxq_desc` and `n_txq_desc`
  rust/src/lib/ifaces/ovs.rs
  rust/src/lib/nm/nm_dbus/connection/ovs.rs
  rust/src/lib/ovsdb/show.rs
  rust/src/lib/unit_tests/ovs.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/ovs_test.py
Labels: Wait_Review

#2198 nm dns: Support arbitrary DNS config
  rust/src/lib/dns.rs
  rust/src/lib/nm/dns.rs
  rust/src/lib/nm/gen_conf.rs
  rust/src/lib/nm/nm_dbus/dbus.rs
  rust/src/lib/nm/nm_dbus/dbus_proxy.rs
  rust/src/lib/nm/nm_dbus/dns.rs
  rust/src/lib/nm/nm_dbus/error.rs
  rust/src/lib/nm/nm_dbus/mod.rs
  rust/src/lib/nm/nm_dbus/nm_api.rs
  rust/src/lib/nm/query_apply/apply.rs
  rust/src/lib/nm/query_apply/dns.rs
  rust/src/lib/nm/query_apply/mod.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/unit_tests/nm/dns.rs
  tests/integration/dns_test.py
Labels: Wait_Review

#2201 nm dns: Fix error when new DNS interface hold IPv6 link local address only
  rust/src/lib/dns.rs
  rust/src/lib/nispor/show.rs
  rust/src/lib/nm/dns.rs
  rust/src/lib/nm/nm_dbus/nm_api.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/query_apply/inter_ifaces.rs
  rust/src/lib/unit_tests/nm/dns.rs
Labels: Wait_Other_PR, Wait_Review

#2202 ipv6: Fix verification error on empty address list
  rust/src/lib/ip.rs
  rust/src/lib/unit_tests/ip.rs
Labels: Wait_Review

#2203 ovs: Fix error when adding internal interface
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/unit_tests/ifaces.rs
  rust/src/lib/unit_tests/ovs.rs
  rust/src/lib/unit_tests/vlan.rs
  tests/integration/ovs_test.py
Labels: Wait_Review

#2208 tests, integ: clean vlan101 interface correctly
  tests/integration/nm/ovs_test.py
Labels: Wait_Review
