Repository nmstate/nmstate, pull requests merged in 2024-01, with the labels that each got.

#2469 hsr: add support to HSR/PRP interface
  examples/hsr0_absent.yml
  examples/hsr0_up.yml
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/hsr.rs
  rust/src/lib/ifaces/mod.rs
  rust/src/lib/lib.rs
  rust/src/lib/nispor/base_iface.rs
  rust/src/lib/nispor/hsr.rs
  rust/src/lib/nispor/mod.rs
  rust/src/lib/nispor/show.rs
  rust/src/lib/nm/nm_dbus/connection/conn.rs
  rust/src/lib/nm/nm_dbus/connection/hsr.rs
  rust/src/lib/nm/nm_dbus/connection/mod.rs
  rust/src/lib/nm/query_apply/device.rs
  rust/src/lib/nm/settings/connection.rs
  rust/src/lib/nm/settings/hsr.rs
  rust/src/lib/nm/settings/mod.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/query_apply/hsr.rs
  rust/src/lib/query_apply/iface.rs
  rust/src/lib/query_apply/mod.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/examples_test.py
  tests/integration/hsr_test.py
Labels: Work_Ongoing

#2508 ovs: Do not skip serializing `allow-extra-patch-ports`
  rust/src/lib/ifaces/ovs.rs
  rust/src/lib/query_apply/ovs.rs
  rust/src/lib/unit_tests/ovs.rs
Labels: Wait_Review

#2505 ip: Do not skip serializing allow-extra-address: false
  rust/src/lib/ip.rs
  rust/src/lib/query_apply/iface.rs
  rust/src/lib/query_apply/inter_ifaces.rs
  rust/src/lib/query_apply/ip.rs
  rust/src/lib/unit_tests/ip.rs
Labels: Wait_Review

#2519 test: Skip HSR test on RHEL 8
  tests/integration/hsr_test.py
Labels: Wait_Review

#2522 test: Skip `test_add_macsec_and_remove_example` on RHEL 8
  tests/integration/examples_test.py
Labels: Wait_Review

#2523 Promote Wen Liang as maintainer
  .github/CODEOWNERS
  nmstate.gpg
Labels: Wait_Review

#2518 ipsec: Add support of P2P IPSec tunnel
  rust/src/lib/ifaces/ipsec.rs
  rust/src/lib/nm/query_apply/vpn.rs
  rust/src/lib/nm/settings/vpn.rs
  tests/integration/ipsec_test.py
Labels: Wait_Review

#2527 rpm: Fix SONAME in RHEL 9 build
  packaging/nmstate.spec.in
Labels: Wait_Review

#2509 net_state: Remove `prop_list`
  rust/src/cli/query.rs
  rust/src/lib/dns.rs
  rust/src/lib/net_state.rs
  rust/src/lib/nispor/show.rs
  rust/src/lib/nm/query_apply/apply.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/ovs.rs
  rust/src/lib/ovsdb/apply.rs
  rust/src/lib/ovsdb/show.rs
  rust/src/lib/query_apply/dns.rs
  rust/src/lib/query_apply/net_state.rs
  rust/src/lib/query_apply/ovs.rs
  rust/src/lib/revert/dns.rs
  rust/src/lib/revert/net_state.rs
  rust/src/lib/revert/ovsdb.rs
  rust/src/lib/statistic/feature/dns.rs
  rust/src/lib/statistic/feature/ovs.rs
  rust/src/lib/unit_tests/dns.rs
  rust/src/lib/unit_tests/ovsdb.rs
  rust/src/lib/unit_tests/policy/capture.rs
  rust/src/lib/unit_tests/policy/net_policy.rs
  tests/integration/nmstatectl_test.py
Labels: Wait_Review

#2532 Makefile: fix python install path for Python >= 3.12
  Makefile
Labels: needs-ok-to-test

#2510 ip: Remove the `prop_list` property
  rust/src/lib/ip.rs
  rust/src/lib/nispor/ip.rs
  rust/src/lib/nm/query_apply/ip.rs
  rust/src/lib/query_apply/ip.rs
Labels: Wait_Review

#2512 base_iface: Remove `prop_list`
  rust/src/lib/ifaces/base.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/nispor/base_iface.rs
  rust/src/lib/nm/query_apply/apply.rs
  rust/src/lib/nm/query_apply/ovs.rs
  rust/src/lib/nm/settings/connection.rs
  rust/src/lib/nm/settings/wired.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/ovsdb/show.rs
  rust/src/lib/query_apply/base.rs
  rust/src/lib/statistic/feature/iface.rs
Labels: Wait_Review
