Repository nmstate/nmstate, pull requests merged in 2024-06, with the labels that each got.

#2695 CI: Install NM-libreswan if not found
  automation/run-tests.sh
Labels: Wait_Review

#2694 linux bridge: Fix incorrect check on whether `vlan-default-pvid` changed
  rust/src/lib/query_apply/linux_bridge.rs
  rust/src/lib/unit_tests/bridge.rs
Labels: Wait_Review

#2682 test: Add IPv6 ipsec tests
  tests/integration/conftest.py
  tests/integration/ipsec_test.py
  tests/integration/testlib/env.py
Labels: Wait_Review

#2693 Validate interface in desired port list of controller
  rust/src/lib/ifaces/inter_ifaces_controller.rs
  rust/src/lib/unit_tests/ifaces_ctrller.rs
  tests/integration/linux_bridge_test.py
Labels: Wait_Review

#2696 dns: Fix error when purging DNS with empty server
  rust/src/lib/dns.rs
  rust/src/lib/nm/dns.rs
  rust/src/lib/nm/query_apply/apply.rs
  rust/src/lib/query_apply/dns.rs
  rust/src/lib/unit_tests/dns.rs
  tests/integration/dns_test.py
Labels: Wait_Review

#2678 route: Add support of static route in kernel mode
  rust/src/lib/nispor/apply.rs
  rust/src/lib/nispor/route.rs
  rust/src/lib/nm/route.rs
  rust/src/lib/nm/route_rule.rs
  rust/src/lib/nm/settings/connection.rs
  rust/src/lib/query_apply/route.rs
  rust/src/lib/route.rs
  rust/src/lib/unit_tests/route.rs
  tests/integration/route_test.py
  tests/integration/static_ip_address_test.py
  tests/integration/testlib/assertlib.py
Labels: Wait_Review

#2680 dns: Support DNS modification in kernel mode
  rust/src/lib/nispor/apply.rs
  rust/src/lib/nispor/dns.rs
  rust/src/lib/nispor/mod.rs
  rust/src/lib/nispor/show.rs
  rust/src/lib/query_apply/net_state.rs
  tests/integration/dns_test.py
Labels: Wait_Review

#2692 base iface: Provide permanent-mac-address when querying
  rust/src/lib/ifaces/base.rs
  rust/src/lib/nispor/base_iface.rs
Labels: Wait_Review

#2643 sriov: add support for drivers-autoprobe
  examples/eth1_with_sriov.yml
  rust/src/lib/ifaces/sriov.rs
  rust/src/lib/nispor/ethernet.rs
  rust/src/lib/nm/settings/sriov.rs
  rust/src/lib/query_apply/sriov.rs
  rust/src/lib/unit_tests/ethernet.rs
  rust/src/lib/unit_tests/sriov.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/sriov_test.py
Labels: Wait_on_submitter, needs-ok-to-test

#2700 rpm SPEC: Fix rust crate build on Fedora
  packaging/nmstate.spec.in
Labels: Wait_Review

#2703 fix(github-actions): fix macOS x86_64
  .github/workflows/release.yml
Labels: needs-ok-to-test

#2708 [nmstate-1.4] CI: Use vault.centos.org for CentOS Stream 8
  packaging/Dockerfile.c8s-nmstate-build
  packaging/Dockerfile.c8s-nmstate-dev
Labels: Wait_Review

#2706 [nmstate-1.4] dns: Do not touch iface DNS when apply identical DNS state
  libnmstate/net_state.py
  tests/integration/nm/dns_test.py
Labels: Wait_Review

#2714 automation: install dnf5 copr module for Rawhide
  automation/run-tests.sh
Labels: ok-to-test

#2717 test: Remove the need of nispor CLI
  packaging/Dockerfile.c9s-nmstate-dev
  packaging/Dockerfile.fed-nmstate-dev:latest
  packaging/Dockerfile.fed-nmstate-dev:rawhide
  tests/integration/linux_bridge_test.py
  tests/integration/nm/linux_bridge_test.py
Labels: Wait_Review

#2707 CI: Remove pylint test
  automation/run-tests.sh
  tox.ini
Labels: Wait_Review
