Repository nmstate/nmstate, pull requests merged in 2024-04, with the labels that each got.

#2638 Fix cargo clippy
  rust/src/lib/unit_tests/route.rs
Labels: Wait_Review

#2641 markdown: Correct badges and fix markdown errors
  README.md
Labels: needs-ok-to-test

#2649 CI container: Sync container with latest repos
  packaging/Dockerfile.c9s-nmstate-build
  packaging/Dockerfile.c9s-nmstate-dev
  packaging/Dockerfile.fed-nmstate-dev:latest
  packaging/Dockerfile.fed-nmstate-dev:rawhide
Labels: Wait_Review

#2639 route: Normalize route table of current route when determining route removed
  rust/src/lib/nm/query_apply/route.rs
  tests/integration/route_test.py
Labels: Wait_Review

#2633 Create alias for nmstaetctl subcommand #2579
  rust/src/cli/ncl.rs
Labels: needs-ok-to-test

#2632 Use Workspace Dependencies #2406
  rust/Cargo.toml
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
Labels: Wait_on_submitter, needs-ok-to-test

#2651 veth: Alway show veth interface with type veth
  rust/src/lib/query_apply/base.rs
  tests/integration/veth_test.py
Labels: Wait_Review

#2611 Hide secrets in Debug trait of NetworkState and its subtypes
  rust/src/lib/ieee8021x.rs
  rust/src/lib/ifaces/ipsec.rs
  rust/src/lib/ifaces/macsec.rs
  rust/src/lib/unit_tests/debug_trait.rs
  rust/src/lib/unit_tests/mod.rs
Labels: Wait_Review, needs-ok-to-test

#2640 cargo: Fix compiling on rust 1.66
  .github/workflows/main.yml
  rust/Cargo.toml
  rust/src/lib/Cargo.toml
Labels: Wait_Review

#2625 Add alias docs(man pages) for nmstatectl subcommands
  doc/nmstatectl.8.in
Labels: needs-ok-to-test

#2660 Fix cargo clippy
  rust/src/lib/unit_tests/debug_trait.rs
Labels: Wait_Review
