Repository nmstate/nmstate, pull requests merged in 2024-03, with the labels that each got.

#2574 ovs: Auto managed ignored OVS port
  rust/src/lib/ifaces/inter_ifaces_controller.rs
  rust/src/lib/unit_tests/ifaces_ctrller.rs
  tests/integration/nm/ovs_test.py
Labels: Wait_Review

#2578 Ignore .vscode
  .gitignore
Labels: needs-ok-to-test

#2567 lint: Remove debug print
  rust/src/lib/unit_tests/policy/error.rs
Labels: Wait_Review

#2569 ovs: Raise invalid argument error when desired OVS bridge with MAC
  rust/src/lib/ifaces/ovs.rs
  rust/src/lib/unit_tests/ovs.rs
Labels: Wait_Review

#2565 statistic: Allowing input multiple desire states
  doc/nmstatectl.8.in
  rust/src/cli/ncl.rs
  rust/src/cli/statistic.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/statistic/inter_ifaces.rs
  rust/src/lib/statistic/net_state.rs
  rust/src/lib/unit_tests/statistic.rs
Labels: Wait_Review

#2590 Fix cargo clippy warnings
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/base.rs
  rust/src/lib/ifaces/bond.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/ifaces/linux_bridge.rs
  rust/src/lib/ifaces/ovs.rs
  rust/src/lib/ip.rs
  rust/src/lib/nispor/apply.rs
  rust/src/lib/nispor/bond.rs
  rust/src/lib/nispor/mptcp.rs
  rust/src/lib/nispor/route_rule.rs
  rust/src/lib/nispor/vlan.rs
  rust/src/lib/nm/dns.rs
  rust/src/lib/nm/query_apply/vpn.rs
  rust/src/lib/nm/route.rs
  rust/src/lib/nm/route_rule.rs
  rust/src/lib/nm/settings/dns.rs
  rust/src/lib/nm/settings/ieee8021x.rs
  rust/src/lib/nm/settings/macsec.rs
  rust/src/lib/nm/settings/ovs.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/ovs.rs
  rust/src/lib/ovsdb/show.rs
  rust/src/lib/query_apply/base.rs
  rust/src/lib/query_apply/bond.rs
  rust/src/lib/query_apply/ethernet.rs
  rust/src/lib/query_apply/hostname.rs
  rust/src/lib/query_apply/hsr.rs
  rust/src/lib/query_apply/infiniband.rs
  rust/src/lib/query_apply/inter_ifaces.rs
  rust/src/lib/query_apply/ip.rs
  rust/src/lib/query_apply/ipsec.rs
  rust/src/lib/query_apply/linux_bridge.rs
  rust/src/lib/query_apply/mac_vlan.rs
  rust/src/lib/query_apply/mac_vtap.rs
  rust/src/lib/query_apply/macsec.rs
  rust/src/lib/query_apply/net_state.rs
  rust/src/lib/query_apply/ovs.rs
  rust/src/lib/query_apply/vlan.rs
  rust/src/lib/query_apply/vrf.rs
  rust/src/lib/query_apply/vxlan.rs
  rust/src/lib/revert/ifaces/base.rs
  rust/src/lib/unit_tests/policy/capture.rs
Labels: Wait_Review

#2585 README: Add public matrix room to contact info
  README.md
Labels: Wait_Review

#2584 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: needs-ok-to-test

#2591 (Fix)Deprecate PrettyState in python API
  rust/src/python/libnmstate/prettystate.py
  tests/integration/linux_bridge_test.py
  tests/integration/ovs_test.py
Labels: ok-to-test

#2595 packaging: Fix rpm build on Fedora
  automation/run-tests.sh
  packaging/nmstate.spec.in
Labels: Wait_Review

#2599 Fix cargo clippy
  rust/src/cli/service.rs
Labels: Wait_Review

#2596 Rust crate documentation
  README.md
Labels: Wait_on_submitter, needs-ok-to-test

#2607 Ignore Generated Directories in .gitignore
  .gitignore
Labels: ok-to-test

#2597 Update CONTRIBUTING.md code structure section
  CONTRIBUTING.md
Labels: needs-ok-to-test

#2563 nm dns: Protect global DNS config in checkpoint
  rust/src/lib/nm/nm_dbus/dbus.rs
  tests/integration/nm/dns_test.py
Labels: Wait_Review

#2612 Add Compilation and Installation steps in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: needs-ok-to-test
