Repository nmstate/nmstate, pull requests merged in 2025-02, with the labels that each got.

#2829 controller: Refer port by profile name
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/bond.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/ifaces/inter_ifaces_controller.rs
  rust/src/lib/ifaces/vrf.rs
  rust/src/lib/unit_tests/identifier.rs
  rust/src/lib/unit_tests/mod.rs
  tests/integration/identifer_test.py
Labels: Wait_Review

#2830 parent: Refer parent by profile name
  rust/src/lib/iface.rs
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/ifaces/inter_ifaces_controller.rs
  rust/src/lib/ifaces/mac_vlan.rs
  rust/src/lib/ifaces/mac_vtap.rs
  rust/src/lib/ifaces/macsec.rs
  rust/src/lib/ifaces/vlan.rs
  rust/src/lib/ifaces/vxlan.rs
  rust/src/lib/unit_tests/identifier.rs
  tests/integration/identifer_test.py
Labels: Wait_Other_PR

#2842 CI: Limit runtime time of CI task to maximum 30 minutes
  .github/workflows/main.yml
Labels: Wait_Review

#2838 test ipsec: Fix overlapping on ipv4 subnet
  tests/integration/ipsec_test.py
  tests/integration/testlib/ipsec.py
Labels: Wait_Review

#2820 rust: Migrate zbus v1 to V5
  .github/workflows/main.yml
  packaging/nmstate.spec.in
  rust/Cargo.toml
  rust/src/cli/Cargo.toml
  rust/src/clib/Cargo.toml
  rust/src/lib/Cargo.toml
  rust/src/lib/nm/checkpoint.rs
  rust/src/lib/nm/nm_dbus/active_connection.rs
  rust/src/lib/nm/nm_dbus/connection/bond.rs
  rust/src/lib/nm/nm_dbus/connection/bridge.rs
  rust/src/lib/nm/nm_dbus/connection/conn.rs
  rust/src/lib/nm/nm_dbus/connection/dns.rs
  rust/src/lib/nm/nm_dbus/connection/ethtool.rs
  rust/src/lib/nm/nm_dbus/connection/hsr.rs
  rust/src/lib/nm/nm_dbus/connection/ieee8021x.rs
  rust/src/lib/nm/nm_dbus/connection/iface_type.rs
  rust/src/lib/nm/nm_dbus/connection/infiniband.rs
  rust/src/lib/nm/nm_dbus/connection/ip.rs
  rust/src/lib/nm/nm_dbus/connection/ipvlan.rs
  rust/src/lib/nm/nm_dbus/connection/loopback.rs
  rust/src/lib/nm/nm_dbus/connection/mac_vlan.rs
  rust/src/lib/nm/nm_dbus/connection/macsec.rs
  rust/src/lib/nm/nm_dbus/connection/mod.rs
  rust/src/lib/nm/nm_dbus/connection/ovs.rs
  rust/src/lib/nm/nm_dbus/connection/route.rs
  rust/src/lib/nm/nm_dbus/connection/route_rule.rs
  rust/src/lib/nm/nm_dbus/connection/sriov.rs
  rust/src/lib/nm/nm_dbus/connection/user.rs
  rust/src/lib/nm/nm_dbus/connection/veth.rs
  rust/src/lib/nm/nm_dbus/connection/vlan.rs
  rust/src/lib/nm/nm_dbus/connection/vpn.rs
  rust/src/lib/nm/nm_dbus/connection/vrf.rs
  rust/src/lib/nm/nm_dbus/connection/vxlan.rs
  rust/src/lib/nm/nm_dbus/connection/wired.rs
  rust/src/lib/nm/nm_dbus/dbus.rs
  rust/src/lib/nm/nm_dbus/dbus_proxy.rs
  rust/src/lib/nm/nm_dbus/dns.rs
  rust/src/lib/nm/nm_dbus/gen_conf/keyfile.rs
  rust/src/lib/nm/nm_dbus/mod.rs
  rust/src/lib/nm/nm_dbus/nm_api.rs
  rust/src/lib/nm/nm_dbus/query_apply/device.rs
  rust/src/lib/nm/query_apply/apply.rs
  rust/src/lib/nm/query_apply/dns.rs
  rust/src/lib/nm/query_apply/ovs.rs
  rust/src/lib/nm/query_apply/profile.rs
  rust/src/lib/nm/show.rs
  rust/src/lib/query_apply/net_state.rs
Labels: Wait_Review

#2845 test: Use openvswitch3.4 for c9s testing
  packaging/Dockerfile.c9s-nmstate-dev
Labels: Wait_Review

#2839 gen_revert: Include current interface if desire is absent
  rust/src/lib/revert/ifaces/iface.rs
  rust/src/lib/unit_tests/gen_revert_test_files/absent_veth/current.yml
  rust/src/lib/unit_tests/gen_revert_test_files/absent_veth/desired.yml
  rust/src/lib/unit_tests/gen_revert_test_files/absent_veth/revert.yml
Labels: Wait_Review

#2813 nm log: Do not use debug print for Option<String>
  rust/src/lib/nm/query_apply/profile.rs
Labels: Wait_Review

#2849 Makefile: Stop generating vendor tarball for rust 1.66
  .github/workflows/msrv.yml
  Makefile
Labels: Wait_Review

#2817 Correct spelling of "extension"
  rust/src/cli/service.rs
Labels: needs-ok-to-test

#2850 route: Add support of initcwnd and initrwnd
  rust/src/lib/nispor/route.rs
  rust/src/lib/nm/nm_dbus/connection/route.rs
  rust/src/lib/nm/settings/route.rs
  rust/src/lib/route.rs
  rust/src/lib/unit_tests/route.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/route_test.py
Labels: Wait_Review

#2816 github/dependabot: Add github-actions & Rust crates updates
  .github/dependabot.yml
Labels: needs-ok-to-test
