Repository nmstate/nmstate, pull requests merged in 2025-07, with the labels that each got.

#2924 bond: add "lacp" alias for 802.3ad
  rust/src/lib/ifaces/bond.rs
  rust/src/lib/unit_tests/bond.rs
Labels: needs-ok-to-test

#2925 route: add support for advmss option
  rust/src/lib/nispor/route.rs
  rust/src/lib/nm/nm_dbus/connection/route.rs
  rust/src/lib/nm/nm_dbus/gen_conf/route.rs
  rust/src/lib/nm/settings/route.rs
  rust/src/lib/route.rs
  rust/src/lib/unit_tests/route.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/nm/gen_conf_test.py
  tests/integration/route_test.py
Labels: needs-ok-to-test

#2928 test: Do not wait infinitely for IPSec server container
  tests/integration/testlib/ipsec.py
Labels: Wait_Review

#2929 rust: fix unused mut in test
  rust/src/lib/unit_tests/bond.rs
Labels: ok-to-test

#2911 interface: ignore interface with state 'unknown'
  rust/src/lib/ifaces/inter_ifaces.rs
  rust/src/lib/unit_tests/ifaces.rs
  rust/src/python/libnmstate/schema.py
  tests/integration/bond_test.py
Labels: needs-ok-to-test

#2934 nm: Bump minimum supported NetworkManager version 1.46
  .github/workflows/main.yml
  .github/workflows/run_test.sh
  rust/src/lib/nm/query_apply/apply.rs
  rust/src/lib/nm/settings/vlan.rs
  tests/integration/bond_test.py
  tests/integration/examples_test.py
  tests/integration/hsr_test.py
  tests/integration/loopback_test.py
  tests/integration/macsec_test.py
  tests/integration/nm/bond_test.py
  tests/integration/nm/gen_conf_test.py
  tests/integration/nm/route_rule_test.py
  tests/integration/nm/route_test.py
  tests/integration/ovs_test.py
  tests/integration/route_test.py
  tests/integration/static_ip_address_test.py
  tests/integration/testlib/env.py
  tests/integration/vlan_test.py
Labels: Wait_Review

#2938 pci: Fix deletion of PCI address identifier config
  rust/src/lib/iface.rs
  tests/integration/pci_identifer_test.py
Labels: Wait_Review

#2939 bond: Fix removing mac-restricted bond
  rust/src/lib/ifaces/bond.rs
  tests/integration/bond_test.py
Labels: Wait_Review

#2945 Change default code owner
  .github/CODEOWNERS
Labels: Wait_Review

#2944 pci: Fix typo `MAC address` vs `PCI address`
  rust/src/lib/ifaces/inter_ifaces.rs
Labels: Wait_Review

#2948 service: Wait on NetworkManager-wait-online.service
  packaging/nmstate.service
Labels: Wait_Review

#2954 rust: fix clippy warning
  rust/src/lib/ovsdb/json_rpc.rs
Labels: ok-to-test

#2962 github: Release @ffmancera from default code owner
  .github/CODEOWNERS
Labels: Wait_Review

#2963 bond: Ignore desired MAC when in MAC restricted mode
  rust/src/lib/ifaces/bond.rs
  rust/src/lib/unit_tests/bond.rs
  tests/integration/bond_test.py
Labels: Wait_Review
