Repository nmstate/nmstate, pull requests merged in 2025-04, with the labels that each got.

#2874 test: Improve ipsec test
  packaging/Dockerfile.c10s-nmstate-dev
  packaging/Dockerfile.c9s-nmstate-dev
  packaging/Dockerfile.fed-nmstate-dev:latest
  packaging/Dockerfile.fed-nmstate-dev:rawhide
  tests/integration/conftest.py
  tests/integration/ipsec_test.py
  tests/integration/test_ipsec_certs/ca.crt
  tests/integration/test_ipsec_certs/hosta.example.org.crt
  tests/integration/test_ipsec_certs/hosta.example.org.key
  tests/integration/test_ipsec_certs/hostb.example.org.crt
  tests/integration/test_ipsec_certs/hostb.example.org.key
  tests/integration/test_ipsec_files/4in6_6in4.conf
  tests/integration/test_ipsec_files/cert_gw.conf
  tests/integration/test_ipsec_files/cli-a.example.org.p12
  tests/integration/test_ipsec_files/host_to_site.conf
  tests/integration/test_ipsec_files/ipsec-srv.example.org.p12
  tests/integration/test_ipsec_files/p2p.conf
  tests/integration/test_ipsec_files/psk_gw.conf
  tests/integration/test_ipsec_files/rsa_gw.conf
  tests/integration/test_ipsec_files/site_to_site.conf
  tests/integration/test_ipsec_files/transport.conf
  tests/integration/testlib/ipsec.py
Labels: Wait_Review

#2875 Python: There is no runtime requirement for setuptools
  rust/src/python/requirements.txt
Labels: needs-ok-to-test

#2876 test: Skip `test_gen_conf_ovs_bridge_port_ref_by_mac` on NM 1.48-
  tests/integration/nm/gen_conf_test.py
Labels: Wait_Review

#2877 packaging: Use cargo vendor for snapshot build on Fedora
  packaging/nmstate.spec.in
Labels: Work_Ongoing

#2884 cargo: Add `--allow-dirty` to script to publishing
  automation/upstream_release.sh
Labels: Wait_Review

#2887 test: Fix `test_dhcp_on_bridge0`
  tests/integration/dynamic_ip_test.py
Labels: Wait_Review
